### ISSUE TITLE
UBERON:0000991 gonad

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#1143]
Hi Chris,

I guess, some contradictory information for mouse development, see below please:

relationship: existence_ends_during_or_before MmusDv:0000025 {gci_filler="NCBITaxon:10090", gci_relation="part_of"} ! Theiler stage 18 (mouse)

relationship: existence_starts_during_or_after MmusDv:0000023 {gci_filler="NCBITaxon:10090", gci_relation="part_of"} ! Theiler stage 16 (mouse)

relationship: existence_starts_during_or_after MmusDv:0000026 {gci_filler="NCBITaxon:10090", gci_relation="part_of"} ! Theiler stage 19 (mouse)

'gonad primordium' is present since TS 18
http://www.emouseatlas.org/emap/ema/theiler_stages/StageDefinition/AnatomyOntology/ts18ontology.html

and 'gonad' at TS 20
http://www.emouseatlas.org/emap/ema/theiler_stages/StageDefinition/AnatomyOntology/ts20ontology.html

ovary and testis are described since TS21

http://www.emouseatlas.org/emap/ema/theiler_stages/StageDefinition/AnatomyOntology/ts21ontology.html

Thank you

Anne

**Comment by tfhayamizu** [comment]
We are working with our collaborators to make public an updated file for the EMAPA. A more recent version is currently in use by GXD/MGI and can be accessed via a browser at: http://www.informatics.jax.org/vocab/gxd/anatomy/<http://www.informatics.jax.org/vocab/gxd/anatomy/EMAPA:16039>

The stage range for the developmental mouse anatomy term 'gonad' EMAPA:17383 has since been revised to "starts_at" TS19: http://www.informatics.jax.org/vocab/gxd/anatomy/EMAPA:17383

We apologize for any problematic issues the delay in release may be responsible for

Sincerely,
Terry



On 9/7/15, 8:40 AM, <notifications@github.com<mailto:notifications@github.com>> wrote:

some contradictory information for mouse development, see below please:

relationship: existence_ends_during_or_before MmusDv:0000025 {gci_filler="NCBITaxon:10090", gci_relation="part_of"} ! Theiler stage 18 (mouse)

relationship: existence_starts_during_or_after MmusDv:0000023 {gci_filler="NCBITaxon:10090", gci_relation="part_of"} ! Theiler stage 16 (mouse)

relationship: existence_starts_during_or_after MmusDv:0000026 {gci_filler="NCBITaxon:10090", gci_relation="part_of"} ! Theiler stage 19 (mouse)

'gonad primordium' is present since TS 18
http://www.emouseatlas.org/emap/ema/theiler_stages/StageDefinition/AnatomyOntology/ts18ontology.html

and 'gonad' at TS 20
http://www.emouseatlas.org/emap/ema/theiler_stages/StageDefinition/AnatomyOntology/ts20ontology.html

ovary and testis are described since TS21

http://www.emouseatlas.org/emap/ema/theiler_stages/StageDefinition/AnatomyOntology/ts21ontology.html

Thank you

Anne

The information in this email, including attachments, may be confidential and is intended solely for the addressee(s). If you believe you received this email by mistake, please notify the sender by return email as soon as possible.

**Comment by cmungall** [comment]
@tfhayamizu the latest version on the JAX FTP site is from last year, but it looks like there are regular edits made in github, and emapa-edit_NO-CL.obo has gonad starting at TS19. Let us know if you want help with the release pipeline. For making uberon [composite-metazoan](https://github.com/obophenotype/uberon/wiki/Multi-species-composite-ontologies#multi-species-composite-modules) should we use what is in github or the ftp site?

**Comment by tfhayamizu** [comment]
I plan to be in Edinburgh the week after next and the issue of developing a better release procedure will definitely be a priority among our discussion points. In the meantime, I will see if we can get the updated file currently in github available at the ftp site.

On 9/7/15, 12:29 PM, <notifications@github.com<mailto:notifications@github.com>> wrote:
@tfhayamizu<https://github.com/tfhayamizu> the latest version on the JAX FTP site is from last year, but it looks like there are regular edits made in github, and emapa-edit_NO-CL.obo has gonad starting at TS19. Let us know if you want help with the release pipeline. For making uberon composite-metazoan<https://github.com/obophenotype/uberon/wiki/Multi-species-composite-ontologies#multi-species-composite-modules> should we use what is in github or the ftp site?

The information in this email, including attachments, may be confidential and is intended solely for the addressee(s). If you believe you received this email by mistake, please notify the sender by return email as soon as possible.

**Comment by ANiknejad** [comment]
now there are no more information for Mouse developemental stages linked to UBERON:0000991 gonad...

**Comment by cmungall** [comment]
Will be fixed in next release. Looks like we have a problem with the download of the emapa file

**Comment by matentzn** [comment]
Looks like this was fixed, but if it was not, please reopen.
