### ISSUE TITLE
move phenoscape-ext.owl into github

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#1194]
multiple advantages: simplification, unified travis job, etc

it could go into its own github repo, or just live in a file alongside the uberon one

**Comment by balhoff** [comment]
Good idea. @wdahdul and I were talking about Sourceforge vs GitHub recently. I think now that there is a user-friendly GitHub Mac app, it might work as well or better than the SVN guis they have been using.

**Comment by mellybelly** [comment]
@cmungall has been tinkering with a plan for all of uberon to be in OWL in github, would make it easier for all of us to contribute ;-)

**Comment by mellybelly** [comment]
@wdahdul i have been using sourcetree, haven't tried the mac app yet, but will do so.

**Comment by balhoff** [comment]
This is the app I was thinking of: https://desktop.github.com

**Comment by wdahdul** [comment]
Moving to github sounds good to me. 
@cmungall i have a few updates to ext planned for this week, so I'll go ahead with the SVN version, but let me know if this conflict with your plans.

**Comment by cmungall** [comment]
I won't do anything til I get the go ahead from you

**Comment by balhoff** [comment]
Phenoscape ext lives here: http://sourceforge.net/p/phenoscape/code/HEAD/tree/trunk/vocab/edit/

How much of that should we move to GitHub? Only two files have been touched since 2013 (the ontology and the ID ranges.

Should it go into this Uberon repository or into its own repository under obophenotype?
* Being in the Uberon repository would make for a lot of extra for curators to clone to their desktop.
* Being separate might complicate things? I am happy to go with @cmungall 's preference.

We are ready to make the move.

**Comment by balhoff** [comment]
@cmungall what did you think about within Uberon repo or in separate?

**Comment by cmungall** [comment]
Let's do separate. Easier to maintain commit history that way, and as you say, easier for editors.

I think it's possible to transfer just a chosen directory using git svn, I can check my notes if you like

**Comment by balhoff** [comment]
Yes I think that's right. I will give it a try. I usually use svn2git.

**Comment by balhoff** [comment]
This is done. I made another issue for changes needed to use the new location: #1202

https://github.com/obophenotype/uberon-phenoscape-ext
