### ISSUE TITLE
trachea gland UBERON_0005203 subclass of UBERON_0011148

### ISSUE THREAD

**Issue by cindyJax** [obophenotype/uberon#1197]
Move 'trachea gland' UBERON_0005203 to be a subclass of 'submucosal gland' UBERON_0011148 instead of 'gland' UBERON_0002530.

Update text definition (suggested): 
Trachea gland is a tubuloacinar seromucous gland that is located principally in the submucosa of the trachea.  Excretory ducts from this gland pass through the lamina propria to the tracheal lumen. These glands secrete mucus, lysozyme, defensins, and other agents that help protect the lungs from particles and infectious agents.
Refs: ISBN:1451113412, PMID:15973734, MGI:Anna and http://medical-dictionary.thefreedictionary.com/tracheal+glands

**Comment by cmungall** [comment]
The classification as 'submucosal gland' should be inferred, if this is purely a location-based grouping; however, following wikipedia we define it based on a combination of location (submucosa) *and* cell-type. Also, location based classification may not be as simple as it at first seems due to glands crossing layers. 

more work needed, see #1201
