### ISSUE TITLE
Relation between "clavicle bone", "shoulder bone" and "shoulder joint"

### ISSUE THREAD

**Issue by fbastian** [obophenotype/uberon#1227]
There are relations that lead to infer that "clavicle bone" exists only in tetrapoda, see: https://github.com/BgeeDB/anatomical-similarity-annotations/issues/12#issuecomment-224921019

Is this relation correct? 
  UBERON_0003461 "shoulder bone" has_part part_of UBERON_0016884 "shoulder joint"
And what is this relation "has_part part_of"?

OWL file: 

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/UBERON_0003461">
        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000051"/>
                <owl:someValuesFrom>
                    <owl:Restriction>
                        <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000050"/>
                        <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/UBERON_0016884"/>
                    </owl:Restriction>
                </owl:someValuesFrom>
            </owl:Restriction>
        </rdfs:subClassOf>
    ...
    </owl:Class>

**Comment by cmungall** [comment]
OK, a few things going on here

The 'source' axiom is:

'shoulder bone' EquivalentTo 'bone element' and overlaps some 'shoulder 
joint'

(let's leave aside the state-specific bone and state-generic 'bone 
element' for the moment)

Formally

overlaps = has_part o part_of

(ie if two things have a part in common, they overlap_

but we can't state this as an OWL axiom, so we expand as a 
meta-reasoning step

Giving us:

'shoulder bone' EquivalentTo 'bone element' and has-part some (part-of 
some 'shoulder joint')

Again ignore the bone/element mismatch, I think this is justifiable, 
albeit circular (the def of shoulder joint references shoulder!)

There are some interesting discussions here about logic and how to 
approach generic-sounding names like 'shoulder' that have a somewhat 
fixed meaning...

but all that aside, the real issue here is:

   'clavicle bone' SubClassOf 'shoulder bone'

This should clearly by a taxon GCI, for the reasons you mention.

And on top of that: why didn't the extensive taxon constraints catch 
this?

**Comment by fbastian** [comment]
Thanks for the explanations, and for the fix.
