### ISSUE TITLE
Version IRI not resolving

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#1234]
The current release has version http://purl.obolibrary.org/obo/uberon/releases/2016-06-12/ext.owl

It returns 404 for me.

**Comment by balhoff** [comment]
This is still the case. :-)

**Comment by cmungall** [comment]
Seems to work for some but not others. This one works:

http://purl.obolibrary.org/obo/uberon/releases/2017-05-21/ext.owl

Currently there is a flaky release process that depends on sf (couldn't use github due to large file sizes). Thankfully there is a clear path forward emerging: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/494

Some retrospective releases may need to be recreated - do you need the 2016-06-12 version specifically?

**Comment by balhoff** [comment]
No - I was just trying to get the last couple versions for a diff test.

**Comment by balhoff** [comment]
This remains a problem with the current release: http://purl.obolibrary.org/obo/uberon/releases/2021-07-27/ext.owl

**Comment by matentzn** [comment]
Oh, this release was still in draft mode, oops. Now it works. Sorry about that!
