### ISSUE TITLE
UBERON:0007329 pancreatic duct and UBERON:0000017 exocrine pancreas in zebrafish 

### ISSUE THREAD

**Issue by fbastian** [obophenotype/uberon#1250]
In composite-metazoan there is a relation: 

    [Term]
    id: ZFA:0005748
    name: intrapancreatic duct (Danio)
    relationship: part_of UBERON:0007329 ! pancreatic duct

But pancreatic duct is not supposed to exist in zebrafish: 

    UBERON:0007329 "pancreatic duct" connected to UBERON:0002114 "duodenum" never_in_taxon NCBITaxon:7955 "Danio rerio"
    UBERON:0007329 "pancreatic duct" connected to UBERON:0002114 "duodenum" continuous with UBERON:0001166 "pylorus" is_a UBERON:0009870 "zone of stomach" part_of UBERON:0000945 "stomach" never_in_taxon NCBITaxon:7955 "Danio rerio"

Similarly: 

    [Term]
    id: ZFA:0005753
    name: pancreatic lobule (Danio)
    relationship: part_of UBERON:0000017 ! exocrine pancreas

But: 

    UBERON:0000017 "exocrine pancreas" has_part UBERON:0007329 "pancreatic duct" connected to UBERON:0002114 "duodenum" never_in_taxon NCBITaxon:7955 "Danio rerio"
    UBERON:0000017 "exocrine pancreas" has_part UBERON:0007329 "pancreatic duct" connected to UBERON:0002114 "duodenum" continuous with UBERON:0001166 "pylorus" is_a UBERON:0009870 "zone of stomach" part_of UBERON:0000945 "stomach" never_in_taxon NCBITaxon:7955 "Danio rerio"

**Comment by cerivs** [comment]
There is a pancreatic duct  in zebrafish and it inserts into the intestinal bulb.  There is no stomach in zebrafish so perhaps the problem is the zone of stomach mentioned above.
From PMID: 15963491 
 The exocrine ductal system arises as branches of the main pancreatic duct that inserts into the
proximal intestine.  We define segments or branches of exocrine tissue and their associated ducts as lobules.  Histological analyses show that the exocrine lobules are comprised of acinar glands and large ducts lined by cuboidal cells.

**Comment by cmungall** [comment]
The issue is that the definition references the duodenum

We should generalize the definition to be functional, as in ZFA 

def: "Duct that collects and carries secretions of the exocrine pancreas." [GOC:cvs, GOC:ymb, ORCiD:0000-0002-2244-7917, ORCiD:0000-0002-9900-7880]

This should work for all species

We can have phylogenetic GCIs for connections in different species (intestinal bulb, duodenum, ...)

**Comment by cmungall** [comment]
generalizing it will also make it fit within our duct pattern: https://github.com/obophenotype/uberon/blob/master/patterns/gland_duct.yaml
