### ISSUE TITLE
property chain between part-of and develops-from causes problems with anatomical surfaces

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#1324]
![image](https://cloud.githubusercontent.com/assets/50745/26556008/d894a3ac-444c-11e7-955d-7aa6d380fdcf.png)

This is a problem because

 1. anatomical surfaces are immaterial
 2. VSOP is asserted to be a surface
 3. VSOP is inferred to be a structure
 4. structures are disjoint from immaterial entities

(aside: why isn't this being picked up at time of release?)

Possible solutions:

 1. remove `part-of o develops-from -> develops-from`
 2. Weaken range of developmental relationships
 3. Don't use part-of (or subprop) to connect IMEs to MEs
 4. Don't use an IME for VSOP and others. E.g treat entities labeled "suface" as being a material surface *layer*

**Comment by mellybelly** [comment]
#4 seems least disruptive

On May 29, 2017, at 6:04 PM, Chris Mungall <notifications@github.com<mailto:notifications@github.com>> wrote:


[image]<https://cloud.githubusercontent.com/assets/50745/26556008/d894a3ac-444c-11e7-955d-7aa6d380fdcf.png>

This is a problem because

  1.  anatomical surfaces are immaterial
  2.  VSOP is asserted to be a surface
  3.  VSOP is inferred to be a structure
  4.  structures are disjoint from immaterial entities

(aside: why isn't this being picked up at time of release?)

Possible solutions:

  1.  remove part-of o develops-from -> develops-from
  2.  Weaken range of developmental relationships
  3.  Don't use part-of (or subprop) to connect IMEs to MEs
  4.  Don't use an IME for VSOP and others. E.g treat entities labeled "suface" as being a material surface layer

**Comment by cmungall** [comment]
But we'll run into issues with things like lumens, it would be a big changes to change all existing lumen classes into being MEs corresponding to the contents of the bona-fide lumens.

I'm in favor of 2, I'm comfortable with using developmental relationships to connect lumens and bona-fide surfaces, @dosumis may be less comfortable with it

**Comment by cmungall** [comment]
Going with 2 for now. It turns out this was a single constraint on has-developmental-contribution-from (develops-from did not have this). We can revisit later.

**Comment by dosumis** [comment]
On 29 May 2017 5:26 pm, "Chris Mungall" <notifications@github.com> wrote:

But we'll run into issues with things like lumens, it would be a big
changes to change all existing lumen classes into being MEs corresponding
to the contents of the bona-fide lumens.

I'm in favor of 2, I'm comfortable with using developmental relationships
to connect lumens and bona-fide surfaces, @dosumis
<https://github.com/dosumis> may be less comfortable with it


Yep.  New relations would be better here.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/obophenotype/uberon/issues/1324#issuecomment-304696600>,
or mute the thread
