### ISSUE TITLE
UBERON:0001987 Placenta infered as owl:Nothing for Opossum (13616)

### ISSUE THREAD

**Issue by jwollbrett** [obophenotype/uberon#1376]
related to : #1309
We used the SpeciesSubsetterUtil class from owltools-0.3.0 in order to create species specific ontologies.
In the Opossum ontology the placenta is missing.

We followed the same strategy than the one used in the SpeciesSubsetterUtil
but directly in protégé i.e We manually added owl:Thing SubclassOf ('in taxon' some 'NCBITaxon_13616') then we run the ELK 0.4.3 reasoner.
* UBERON:0001987 "placenta" only_in_taxon NCBITaxon:9347 "Eutheria” 

The opossum is not an Eutheria but a Metatheria

**Comment by cmungall** [comment]
OK, looks like TC is too strict.

E..g

http://www.ucmp.berkeley.edu/mammal/eutheria/placental.html

"The term "placental mammals" is somewhat of a misnomer because marsupials also have placentae. The difference is that the placenta of marsupials is very short-lived and does not make as much of a contribution to fetal nourishment as it does in eutherians, as "placental mammals" are known scientifically."
