### ISSUE TITLE
id duplication for UBERON:0011953

### ISSUE THREAD

**Issue by cmpich** [obophenotype/uberon#1404]
The following term stanza has the first 'id:' line duplicated in the obo file:
(http://ontologies.berkeleybop.org/uberon/basic.obo)

[Term]
id: UBERON:0011953
id: UBERON:0011953
name: stomach glandular region
def: "A region of the stomach that is lined with glandular epithelium." [http://orcid.org/0000-0002-6601-2165]
subset: pheno_slim
synonym: "glandular stomach" RELATED []
xref: EMAPA:17623
xref: http://linkedlifedata.com/resource/umls/id/C0227197
xref: http://www.snomedbrowser.com/Codes/Details/27633001
xref: MA:0001613
xref: NCIT:C77661
xref: UMLS:C0227197 {source="ncithesaurus:Glandular_Stomach"}
is_a: UBERON:0009870 ! zone of stomach

**Comment by cmungall** [comment]
`curl -L http://ontologies.berkeleybop.org/uberon/basic.obo | grep '^id: UBERON:0011953' | wc`

returns 1

as does the official PURL:

`curl -L http://purl.obolibrary.org/obo/uberon/basic.obo  | grep '^id: UBERON:0011953' | wc`

The file has not changed since 2017-12-01, can you check exactly what happened at your end?

**Comment by cmpich** [comment]
Looks like something went wrong on my side.
All looks good. Closing.
