### ISSUE TITLE
cochlear labyrinth located in vs part of cochlea

### ISSUE THREAD

**Issue by tgbugs** [obophenotype/uberon#1513]
Is there a reason why [cochlear labyrinth](http://purl.obolibrary.org/obo/UBERON_0002499) is located in [cochlea](http://purl.obolibrary.org/obo/UBERON_0001844) as opposed to part of cochlea? Use of located in breaks the ability to traverse anatomical partonomies and the use of part of seems to be factually correct and consistent with the use and definition of located in in this case.

**Comment by dosumis** [comment]
I think this is correct. We will need to break the part_of chain somewhere above the sensory epithelium, because this breaks spatial disjointness between the skeletal and nervous systems.  It looks to me like this is the right place to break the chain - the labyrinth is bounded by bone, not part of it.

Closing - please re-open if you disagree.
