### ISSUE TITLE
Clarification on CL:0000477 (follicle cell)

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/uberon#1524]
Hi,
Uberon used to have UBERON:3010289 obsolete follicle cell, and this is now obsolete and replaced by CL:0000477 (follicle cell), but I can't see that that's used in Uberon. Asking because we are reviewing the same term in EFO and are trying to figure out if it should be retired or better defined. Please see https://github.com/EBISPOT/efo/issues/599.
Thanks,
Paola

**Comment by nicolevasilevsky** [comment]
This term has the exact synonym 'ovarian follicle cell', so I think it could be textually defined as:
A cell that is part of an ovarian follicle.

We could add the SubClass Of axiom 
'part of' some 'ovarian follicle'

Would this the correct approach?

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
Thanks for your feedback. Your suggestion sounds good to me. However, I'm concerned that CL:0000477 follicle cell has a FlyBase dbxref, and has 2 children and both have FlyBase dbxrefs, while UBERON 'ovarian follicle' seems to cover vertebrates only. So I'd like to make sure that it's ok to use the CL term as is for mammals, basically. Thanks! :-)

**Comment by nicolevasilevsky** [comment]
I would think so, as far as I understand, CL is meant to be cross-species as well.

@cmungall or @dosumis please correct me if I am wrong.

I will do a PR to CL to add the text def to follicle cell.

**Comment by cmungall** [comment]
Let's be very careful here. Remember that CL was created originally a long time ago and many of these undefined terms are very vague as to whether they represent a particular vague grouping.

I bet this part of CL was just copied from FBbt without thinking much about species specificity

Note also that GO uses the string "follicle cell" and the CL ID to define "ovarian follicle cell migration" which does not have taxon constraints of its own but has only been used for Drosophila so far
http://amigo.geneontology.org/amigo/term/GO:0007297

Recall also that in CL a species xref means subclass.

Your proposed text definition and axiom (#596) would render this to be inapplicable to insects since the uberon ovarian follicle is likely vertebrate specific by virtual of its axioms.

So unfortunately you have inherited a bit of a multi-ontology mess here

I think we need to go back to first principles and ask how we want to model this. Is there a sense in grouping insect and mammal cells here? After that we can decide whether we can inject definitions vs the safer option of obsoleting (which would need to be coordinated with GO)

**Comment by dosumis** [comment]
Hmm - I've merged the pull request - but think more work needed here to distinguish mammalian and arthropod terms.

I was hoping we could refer to 'follicular epithelial cells' to distinguish the arthropod case, but it seems that follicular cells of the mammalian ovary are also considered epithelial:

https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002174&viewMode=All&siblings=false

If we want to keep a general term - (perhaps make a new term for this to avoid confusion?): An epithelial somatic cell associated with a maturing oocyte.

For the arthropod case (rename CL_0000477?) -> follicle cell of egg chamber.  Note - this appears to be duplicate with [CL_0002174](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002174&viewMode=All&siblings=false) and so should be merged.

**Comment by nicolevasilevsky** [comment]
@dosumis I see you merged the PR with unmerged commits. I don't see the text def in the cl-edit.owl file.

The proposed action items above are for the CL, right? This is the Uberon tracker.

I'm getting really confused - could you outline what changes are needed and I'd be happy to make the edits.

Thanks!

**Comment by paolaroncaglia** [comment]
@dosumis 
Could you comment on this one, please?
Thanks.

**Comment by gouttegd** [comment]
This is the same issue than #476 and obophenotype/cell-ontology#589, which have now been fixed.
