### ISSUE TITLE
NTR New Term Request Wall of Gallbladder

### ISSUE THREAD

**Issue by anuwatpe** [obophenotype/uberon#1581]
Wall of Gallbladder: FMA_14657
http://purl.obolibrary.org/obo/FMA_14657
I would like to add a term equivalent to wall of gallbladder in FMA.

Thanks
Anuwat
@addiehl

**Comment by cmungall** [comment]
Hi @anuwatpe 

Sorry for the delay. If terms such as "wall of X" are useful to the community we can add them. But do you mind if ask what is your use case here? Can you not just use "gallbladder"? All parts of the gallbladder that are not part of the lumen are parts of the wall (and that's a pretty abstract distinction)

One use case I can foresee is for concepts like 'thickness of gallbladder wall' it's useful to have the wall term to avoid confusing with e.g. overall width of the structure.

**Comment by addiehl** [comment]
Hi Chris,

Anuwat is working with me on an application ontology for annotation of a dataset from Thailand on cholangiocarcinoma.  One of the data items has to do with thickening of the wall of the gallbladder.  While we realize the wall is a composite structure, for which we could develop a class specific to our ontology, because it is represented in FMA, we wondered if Uberon would consider adding an analogous class.  We of course could use the FMA class, but we are trying to use Uberon for all the anatomical terms we use to limit the mixing of hierarchies as much as possible.

As you point out, we may need to develop a phenotype term or terms as well for which it would be good to have a base anatomical term.

Thanks,
Alex

**Comment by cmungall** [comment]
Thanks, and sorry for the delay. The use case makes sense. We should create wall of X terms more globally.

Btw, if you are using pre-composed quality terms like "thickness of gallbladder wall" you may want to consider oba
