### ISSUE TITLE
NTR: arteriole of small intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1729]
**Preferred term label:**
arteriole of small intestine

**Synonyms**
small intestine arteriole

**Definition (free text, please give PubMed ID)**
Arteriole of villus of small intestine. Arterioles are the smallest division of artery located between the muscular arteries and the capillaries[GO]. [ http://amigo.geneontology.org/amigo/term/GO:0014830 ]. Arterioles rapidly respond to vasoconstrictor and vasodilator stimuli. (https://doi.org/10.1016/B978-0-12-374530-9.00022-X)

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
digestive system arteriole (NTR request here needed?; arteriole UBERON:0001980) 

**Your nano-attribution (ORCID)**
orcid.org/0000-0003-4183-8865/

**Comment by ngeorgeebi** [comment]
@paolaroncaglia please tag with SCA thanks!

**Comment by paolaroncaglia** [comment]
Hi @ngeorgeebi ,
A few questions please:

> **Preferred term label:**
> arteriole of small intestine
> 
> **Synonyms**
> small intestine arteriole
> 
> **Definition (free text, please give PubMed ID)**
> Arteriole of villus of small intestine. Arterioles are the smallest division of artery located between the muscular arteries and the capillaries[GO]. [ http://amigo.geneontology.org/amigo/term/GO:0014830 ]. Arterioles rapidly respond to vasoconstrictor and vasodilator stimuli. (https://doi.org/10.1016/B978-0-12-374530-9.00022-X)

Thanks, but we don't need to include details about arterioles in general here - they'd pertain to 'arteriole' UBERON:0001980. If you know of any publication (possibly associated to a dataset) that looks at/analyses this particular anatomical location, please provide its PMID, otherwise I'll just use your ORCID.
 
> **Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
> digestive system arteriole (NTR request here needed?; arteriole UBERON:0001980)

A new term 'digestive system arteriole' is not strictly needed here - the new term 'arteriole of small intestine' will classify as a descendant of 'digestive system' anyway. We would only add 'digestive system arteriole' if it were useful for your anatomograms or for other projects. @dosumis any opinion? Uberon already has 'respiratory system arteriole'.

@dosumis I'm also wondering if we should tag 'arteriole of small intestine' (and similar new terms requested by Nancy, see #1730 and more recent ones) with location_grouping. We have that subset in CL but not in Uberon.

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Note for self: I've started to add this term and its "siblings" in an uncommitted branch "Nancys_NTRs_1729_to_1736".

**Comment by dosumis** [comment]
* Agree that grouping terms could get excessively abstracted.  I'd limit them to where they are useful.  Danger of combinatorial explosion otherwise.   So hold of on arteriole of digestive system unless required (by SCA).
* I'd be interested to see how effective definitions of the form x_part_of some  y are for grouping the vasculature by location.  Other relations are sometimes used.  This shouldn't stop you adding them though.  We will need to review as part of general work on vasculature for CCF. 
* No harm in adding the location grouping tag.

**Comment by paolaroncaglia** [comment]
Notes for self:
- [ ] Look more in depth at logical defs for vasculature by location (what relations are used; does reasoner classify effectively);
- [ ] Add location_grouping subset tag in Uberon [same as done previously for CL](https://github.com/obophenotype/cell-ontology/pull/808/commits/5663e000847a9b23aa79402fb1ad6add0493a37f).

**Comment by ngeorgeebi** [comment]
thanks @paolaroncaglia  and @dosumis for the questions sorry for the delayed reply!
To answer your questions:
1. PMID - we don't have a specific publication specifically for arterioles in the digestive system - so please just use my orcid ID
2. We do need this term for SCA as there is an image for it that requires the tag

Hope this answers everything but feel free to ping me if more :)

**Comment by paolaroncaglia** [comment]
Note for self: I confirmed with Nancy that they don't need 'digestive system arteriole'.

**Comment by paolaroncaglia** [comment]
Note for self:
- [ ] I might need to come back to this when the [villus of small/large intestine issue](https://github.com/obophenotype/uberon/issues/1733#issuecomment-773259573) is resolved.

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
Your requested term is UBERON:8410004 small intestine arteriole.
Will be available at the next Uberon release. 
Note for self: 
- [ ] When the [villus of small/large intestine issue](https://github.com/obophenotype/uberon/issues/1733#issuecomment-773259573) is resolved, see if the "intersection_of: part_of UBERON:0001213 ! intestinal villus" for UBERON:8410004 small intestine arteriole needs to refer to a more granular term.
