### ISSUE TITLE
NTR: arteriole of large intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1733]
Preferred term label:
arteriole of large intestine

Synonyms
large intestine arteriole

Definition (free text, please give PubMed ID)
Arteriole of villus of large intestine. Arterioles are the smallest division of artery located between the muscular arteries and the capillaries[GO]. [ http://amigo.geneontology.org/amigo/term/GO:0014830 ]. Arterioles rapidly respond to vasoconstrictor and vasodilator stimuli. (https://doi.org/10.1016/B978-0-12-374530-9.00022-X)

Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)
digestive system arteriole (NTR request here needed?; arteriole UBERON:0001980)

Your nano-attribution (ORCID)
orcid.org/0000-0003-4183-8865/

**Comment by ngeorgeebi** [comment]
@paolaroncaglia please add SCA tag

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
Your suggested def says "Arteriole of _villus_ of large intestine". Could you please confirm that you meant to refer to/have anatomical evidence for villi in the large intestine? Asking because the Uberon def of 'large intestine' says "A subdivision of the digestive tract that connects the small intestine to the cloaca or anus. _Lacks or has few villi_[Kardong]." and the existing Uberon term for 'intestinal villus' has a general class axiom pointing specifically at _small intestine_ ('intestinal villus' and ('part of' some 'Homo sapiens') SubClassOf 'part of' some 'mucosa of small intestine'). So depending on your answer, we may need to make a few extra changes. Thanks.

**Comment by ngeorgeebi** [comment]
Thanks @paolaroncaglia and once again I'm sorry for the delayed reply.  As for your question, the zoom in for the large intestine focuses on one of the villi located in the tract - hence the requirement for the term. One of the research focuses for the Gut Atlas is the role of villi in the large intestine - they are morphologically distinct to those in the small intestine.
Therefore it may make sense to rearrange the ontology hierarchy to have intestinal villus as a separate term with small intestine villus and large intestine villus as child terms.

Apologies for the delayed reply and let me know if you've got other questions, thanks!

**Comment by sfexova** [comment]
hi @paolaroncaglia, can we please change this term to 'arteriole of colon' and make it a child term of colon  - UBERON:0001155 colon

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410015 arteriole of colon
