### ISSUE TITLE
NTR: high endothelial venule

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1754]
**Preferred term label:**
high endothelial venule

**Synonyms**

**Definition (free text, please give PubMed ID)**
High endothelial venules are specialized blood vessels adapted for lymphocyte trafficking. They form a spatially organized network, which controls both the type of lymphocyte and the site of entry into lymphoid tissues. Uniquely, high endothelial venules express vascular addressins that regulate lymphocyte entry into lymphoid organs. They perform this function in all lymphoid organs except the spleen. https://pubmed.ncbi.nlm.nih.gov/28217126/

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
lymphoid tissue http://purl.obolibrary.org/obo/UBERON_0001744

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by sfexova** [comment]
Hi, we need this term connected to lymph node for the anatomograms, but it is a general feature of all lymphoid organs, so probably cleanest to create another term specific to lymph node?

**Comment by paolaroncaglia** [comment]
Note to self:
- [ ] Add HEV as an acronym-type synonym (based on same PMID provided above)

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,

> Hi, we need this term ['high endothelial venule'] connected to lymph node for the anatomograms, but it is a general feature of all lymphoid organs, so probably cleanest to create another term specific to lymph node?

Yes, I see you've made separate requests for 'high endothelial venule of lymph node/Peyer's patch/appendix' and that's correct. The PMID you provided states that "high endothelial venules (HEVs) perform this function in all lymphoid organs except the spleen", so I can't link 'high endothelial venule' to 'lymphoid tissue' as you initially asked, because lymphoid tissue includes spleen so the assertion would be incorrect. I'll create a parent term for 'high endothelial venule' and specific children for lymph node/Peyer's patch/appendix.

**Comment by paolaroncaglia** [comment]
@sfexova 
The new term is 
UBERON:8410037 high endothelial venule

**Comment by paolaroncaglia** [comment]
Note to self:
I'll keep this ticket open to address the remaining edits in https://github.com/obophenotype/uberon/issues/1754#issuecomment-853658757.
