### ISSUE TITLE
consistency in tooth terms

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1757]
**Uberon term**
Molar tooth or Premolar tooth. Some have "tooth" in the name, some don't. Some have the number written out (fourth) and some have the number itself (4). Which is preferred? I'm happy to edit it and submit a pull request (for my own use it'd be helpful if they were consistent).

**Bug description**

**Comment by megbalk** [comment]
this may be answered in issue #1848 
However, I'd still like to know what is preferred.

**Comment by megbalk** [comment]
preference is what is used in the literature
make sure other form is a synonym

**Comment by megbalk** [comment]
@markengelstad what is the standard here:
* molar tooth 1 or first molar tooth
* deciduous molar tooth 1 or deciduous first molar tooth
* upper primary molar tooth 1 or upper first primary molar tooth

**Comment by markengelstad** [comment]
Hi!

To answer your options directly:


  *   first molar tooth
  *   deciduous first molar tooth
  *   upper first primary molar tooth
In my knowledge graph, I’ve settled on the following for teeth:

“Secondary upper right first molar tooth”
1: the dentition:  Primary/ Secondary.  I use secondary because teeth aren’t ‘permanent’ and, if you are going to use ‘Permanent’, then why isn’t the primary dentition called “Temporary”?  Anyway, Primary/ Secondary is consistent. “Permanent upper right first molar tooth” is just a synonym.
2: the jaw – upper or lower.  NOT mandibular or maxillary.  Everything dental related is upper / lower.
3: side:  right/ left.
4: the tooth:  ‘second premolar tooth’.

You might not be able to make this designation work for you, but it creates the least amount of confusion/ most consistency with the largest number of tooth naming designations.

Mark


From: Meghan Balk ***@***.***>
Date: Monday, August 22, 2022 at 11:11 AM
To: obophenotype/uberon ***@***.***>
Cc: Mark Engelstad ***@***.***>, Mention ***@***.***>
Subject: Re: [obophenotype/uberon] consistency in tooth terms (#1757)

@markengelstad<https://github.com/markengelstad> what is the standard here:

  *   molar tooth 1 or first molar tooth
  *   deciduous molar tooth 1 or deciduous first molar tooth
  *   upper primary molar tooth 1 or upper first primary molar tooth
