### ISSUE TITLE
NTR: lymph node follicle marginal zone

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1767]
**Preferred term label:**
lymph node follicle marginal zone

**Synonyms**
marginal zone of lymph node; marginal zone of lymph node follicle; lymph node marginal zone

**Definition (free text, please give PubMed ID)**
Histologically, the marginal zone pattern of the lymph node is characterized by lymphoid follicles with three distinct layers. The inner layer is composed of follicular center zones, the middle layer of darkly stained mantle zones, and the outer layer of marginal zones. However, the marginal zone pattern is rarely seen in reactive lymph nodes except for mesenteric lymph nodes. Lymph node marginal zones are populated by marginal zone B cells which express CD19 and CD20
and have the phenotypic features of memory B cells. PMID: 12076268 PMID: 11026094

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
lymph node follicle: http://purl.obolibrary.org/obo/UBERON_0010748

**Your nano-attribution (ORCID)**
orcid.org/0000-0003-4183-8865/

**Comment by ngeorgeebi** [comment]
Thanks @paolaroncaglia  and sorry for the long description.

**Comment by ngeorgeebi** [comment]
dunno whether we should make this a child of mesenteric lymph node too?

**Comment by paolaroncaglia** [comment]
@addiehl may I ask for your feedback here please?
(Cc @ngeorgeebi and @sfexova )

Nancy requested 'lymph node follicle marginal zone' for the Single Cell Atlas anatomograms, see https://github.com/obophenotype/uberon/issues/1767#issue-796938230. I'm unsure if this is in scope for Uberon as the two references provided seem to refer to pathologies (I don't have access to their full texts at the moment). If it's in scope, should it be a child of 'lymph node _secondary_ follicle'?

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Actually, even if it's in scope, it couldn't be a child/descendant of 'lymph node follicle' as it's not observed in all lymph nodes, as per suggested definition.

**Comment by addiehl** [comment]
The marginal zone is present in mesenteric lymph nodes and can be found in other lymph nodes (and the spleen).  It is a natural part of the lymph node anatomy, though not present in all lymph nodes.  It is true that B-cell lymphomas can accumulate in the marginal zone due to aberrant cellular targeting signals, but this does not mean the marginal zone does not belong in Uberon, as it is not a pathological structure per se.  Also, the 'lymph node follicle marginal zone' can have a part_of relationship to 'lymph node' and is_a 'lymphoid tissue', because when it is present it is always part of the lymph node.

We should not limit it to mesenteric lymph node as it can sometimes be seen in other lymph nodes as well.

--Alex

**Comment by paolaroncaglia** [comment]
Hi @addiehl ,

> The marginal zone is present in mesenteric lymph nodes and can be found in other lymph nodes (and the spleen). ... Also, the 'lymph node follicle marginal zone' can have a part_of relationship to 'lymph node' and is_a 'lymphoid tissue', because when it is present it is always part of the lymph node.

Thanks for your feedback. I made a pull request. One last question though, if 'lymph node follicle marginal zone' is part_of 'lymph node' rather than 'lymph node follicle', should the label be 'lymph node marginal zone' instead, with 'lymph node follicle marginal zone' being a narrow synonym? Or did you mean that 'lymph node follicle marginal zone' should be part_of 'lymph node _follicle_' as @ngeorgeebi suggested?

BTW, 'lymphoid follicle' is undefined in Uberon, which doesn't help, would you like to suggest a definition? That term has some comments, too.

Thanks again,
Paola

**Comment by paolaroncaglia** [comment]
Hi @ngeorgeebi (and @sfexova ),
The new term is UBERON:8410065 lymph node follicle marginal zone. 
Will be available with the next release of Uberon.

**Comment by paolaroncaglia** [comment]
Hi @addiehl ,
I created UBERON:8410065 'lymph node follicle marginal zone' as follows:

id: UBERON:8410065
name: lymph node follicle marginal zone
def: "Histologically, the marginal zone pattern of the lymph node is characterized by lymphoid follicles with three distinct layers. The inner layer is composed of follicular center zones, the middle layer of darkly stained mantle zones, and the outer layer of marginal zones. However, the marginal zone pattern is rarely seen in reactive lymph nodes except for mesenteric lymph nodes. Lymph node marginal zones are populated by marginal zone B cells which express CD19 and CD20 and have the phenotypic features of memory B cells." [http://orcid.org/0000-0003-4183-8865/, PMID:11026094, PMID:12076268]
synonym: "lymph node marginal zone" BROAD []
synonym: "marginal zone of lymph node" BROAD []
synonym: "marginal zone of lymph node follicle" EXACT []
is_a: UBERON:0001744 ! lymphoid tissue
relationship: part_of UBERON:0000029 ! lymph node

if 'lymph node follicle marginal zone' is part_of 'lymph node' rather than 'lymph node follicle', should the label be 'lymph node marginal zone' instead, with 'lymph node follicle marginal zone' being a narrow synonym? Or did you mean that 'lymph node follicle marginal zone' should be part_of 'lymph node _follicle_' as @ngeorgeebi suggested?

BTW, 'lymphoid follicle' is undefined in Uberon, which doesn't help, would you like to suggest a definition please?

Thank you,
Paola

**Comment by paolaroncaglia** [comment]
Hi @addiehl ,

Sorry to bug you, but when you have a chance, could you please look at my questions in the [comment above](https://github.com/obophenotype/uberon/issues/1767#issuecomment-873023719), please? Needed to address this ticket as well as a [related CL request](https://github.com/obophenotype/cell-ontology/issues/975), for the Single Cell Atlas anatomograms. Many thanks!

Paola

**Comment by paolaroncaglia** [comment]
The terms needed for SCA have been added, so I'll close this ticket. There may still be room for improvement around 'lymph node follicle marginal zone' (see https://github.com/obophenotype/uberon/issues/1767#issuecomment-873023719), but it may also be ok as is, and we probably don't have enough resources atm, so I'll leave it as is.
