### ISSUE TITLE
Revise relationships between functional zones of hepatic acinus and structural regions of liver lobule

### ISSUE THREAD

**Issue by mkeays** [obophenotype/uberon#1790]
**Uberon term**
The three zones of the hepatic acinus and the three regions of liver lobule.
UBERON:8400001
UBERON:8400002
UBERON:8400003
UBERON:8400006
UBERON:8400007
UBERON:8400008

**Suggested revision of logical definition**
The acinus and its zones are functional concepts while the lobule and its regions are structural, though there is overlap between them and they are often used interchangeably -- the acinus zone 1 is generally found in the periportal region of the lobule. More detail [here](https://github.com/obophenotype/uberon/issues/1648#issuecomment-701433667) in #1648. Had added them as related synonyms to each other (e.g. `hepatic acinus zone 1` `has_related_synonym` `liver lobule periportal region`) but this may not be ideal -- 
From @davidos: Might be too confusing to have, for example, hepatic acinus zone 3 as a primary label and a related synonym on a different term - although I can understand why you'd do it given usage. Could we make an explicit relationship - e.g. overlaps and clarify relationship to usage in a comment?

**Comment by paolaroncaglia** [comment]
Hi @mkeays ,
I'd suggest the following strategy:
- [ ] Use the 'overlaps' object property as @dosumis suggested. See the "Class Usage" tab in Protege for syntax. There is even a more granular property, 'spatially coextensive with', but it may be too stringent for your case as it's defined "x spatially_coextensive_with y if and inly if x and y have the same location". (@dosumis who should we ask to fix the typo in RO? inly -> only) 
- [ ] Remove the related synonyms.
- [ ] Instead, add a gloss to definitions to mention the overlap (e.g. the functionally-defined acinus zone 1 is generally found in the structurally-defined periportal region of the lobule, or similar). This may also help with text searches. It will be redundant with the overlap axiom, but will make usage rationale clearer for curators.
- [ ] Add taxon annotation properties to the terms to clarify to what extent the overlap may be known, e.g. present in taxon or taxon notes.

If the issue is still unresolved, perhaps it could be added to the [agenda](https://docs.google.com/document/d/1XvMbNvr0FEsdqGhg79BYCYEHSqUxRHMcvhbGizEAht8/edit) for the Uberon editors call on March 22nd.

**Comment by mkeays** [comment]
Thanks @paolaroncaglia , I thought I had tried to use 'overlaps' and Protege didn't allow it but now I've tried again it has autocompleted and seems to work!

**Comment by mkeays** [comment]
I think the concept is known about at least in mammalian livers, possibly birds as well, so not sure which taxa to include. E.g. this from WikiVet, covering various mammals and avian liver: https://en.wikivet.net/Liver_-_Anatomy_%26_Physiology#Acinus

**Comment by mkeays** [comment]
More on taxa, from [Hardman et al (2007)](https://anatomypubs.onlinelibrary.wiley.com/doi/full/10.1002/ar.20524):

> The “classic” and “portal” lobule, and liver “acinus” characterize mammalian hepatobiliary structure/function relationships. A “tubular” concept has been used to describe the lower vertebrate livers of birds, fish, reptiles, and amphibians.

So, probably acinus is just a concept used for mammalian livers then. So I could add `'in taxon' some Mammalia` ?

**Comment by paolaroncaglia** [comment]
@mkeays 
I think the correct property to use is the annotation property 'present in taxon' rather than the object property 'in taxon'. Based on their class usage in Protege. I agree that it's slightly confusing.

**Comment by mkeays** [comment]
Thanks @paolaroncaglia , I see it now.

I'm also wondering if I should revise the definition of [metabolic zone of liver](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_8400005) now because it refers to this acinus concept which now I understand to be only relevant in mammals although other non-mammalian species also have metabolic zonation of their livers too.

**Comment by paolaroncaglia** [comment]
@mkeays 

> I'm also wondering if I should revise the definition of [metabolic zone of liver](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_8400005) now because it refers to this acinus concept which now I understand to be only relevant in mammals although other non-mammalian species also have metabolic zonation of their livers too. I think the current definition is OK if I replace "hepatic acinus" with "liver".

Yes, always safer to keep terms as species-agnostic as possible, and there's no current taxon annotation on the term. My suggestions:
"Any of the metabolic zones found in the hepatic acinus [replace "hepatic acinus" with "liver" as you propose]. Liver tissue is heterogenous at the level of morphometry and histochemistry. This heterogeneity is linked to the position of a cell within the functional unit of the tissue, which, in turn, is related to the blood supply: Cells [C -> c] located in the upstream zone differ from those in the downstream zone with respect to subcellular structures, key enzymes, translocators, and receptors and, therefore, have different metabolic capacities. This is the basis for "metabolic zonation", a concept first proposed [in what species/taxon?] for carbohydrate metabolism and later expanded to include amino acid and ammonia metabolism, xenobiotic metabolism, protective metabolism, and formation of plasma proteins."

Also, the creation date looks unusual, possibly due to an incorrect setting? There aren't others like it though: 
202z-09-29T15:45:36Z

Thanks,
Paola

**Comment by dosumis** [comment]
@paolaroncaglia wrote:

> I think the correct property to use is the annotation property 'present in taxon' rather than the object property 'in taxon'. Based on their class usage in Protege. I agree that it's slightly confusing.

@cmungall - I'm using 'in taxon' elsewhere.  IIRC we working working on centralising doc for this.  Can you point us to the latest?

**Comment by balhoff** [comment]
A 'present in taxon' annotation would translate to a some-some, instance-level assertion of `in_taxon`. "There exists some instance of this structure `in_taxon` X." We are using this in GO to assert that a term is meant to be usable in a particular taxon, in case there is a chance that someone might later make an `in_taxon` class axiom on a related class that could conflict with this usage. We have a build step that generates the instance axioms to check that everything is consistent. So if the intent is to say that all instances of the concept are in taxon X, then I would make an ordinary existential restriction.

**Comment by dosumis** [comment]
> If the intent is to say that all instances of the concept are in taxon X, then I would make an ordinary existential restriction.

I think that is the intent here.  It certainly is for the cell types we're adding.

**Comment by paolaroncaglia** [comment]
@dosumis 
@balhoff 
Good morning and thank you both for your feedback. For the benefit of the broader curator community, may I please suggest that 

- Documentation is made available on the above, and if it exists already, please remind us where to find it :-) 
- Documentation includes at least one practical example (ideally one each of cases where one should and shouldn't use a particular property) (also see my question below) 
- Documentation includes minimal instructions and/or a screenshot showing how to add the property in Protege (apologies if this sounds silly, but it seems that at least two of us had trouble at some point in adding axioms that sounded straightforward)

In @mkeays 's case above, my understanding is that 'metabolic zone of liver' exists in all instances of mammals (as long as they're physically healthy and normally developed). However, 'metabolic zone of liver' may exist in non-mammalian species, we just don't know enough. So should Maria use 'present in taxon' rather than 'in taxon', so if anyone else ever wants to apply the term to non-mammals, that won't be flagged as an error? 

Thanks,
Paola

**Comment by dosumis** [comment]
Thanks @paolaroncaglia  - your description makes clear that 'present in taxon' would be the correct one to use.  Strongly agree we need centralised doc.  We have this: https://ontology-development-kit.readthedocs.io/en/latest/TaxonRestriction.html. but clearly not sufficient.  Lets put it on an meeting agenda.

**Comment by paolaroncaglia** [comment]
Thanks @dosumis , I added to today's CL editors meeting agenda.

**Comment by mkeays** [comment]
Thanks @paolaroncaglia ! Will add some more about the metabolic zonation concept and species from original papers.
Weird about the date, thanks for spotting it, I've fixed it in my checkout now.
