### ISSUE TITLE
NTR: lymph node interfollicular cortex

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1809]
**Preferred term label:**
lymph node interfollicular cortex

**Synonyms**
interfollicular cortex of lymph node

**Definition (free text, please give PubMed ID)**
Follicules in the lymph node are surrounded and separated by the interfollicular cortex. Together with the lymph node follicle, the interfollicular cortex of the lymph node lobule make up the superficial cortex of the lymph node. Capillaries empty into the high endothelial venules located in the interfollicular cortex. The interfollicular cortex also serves as transit corriders for lymphocytes migrating between the B and T cell areas. PMID: 17067937

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
lymph node: http://purl.obolibrary.org/obo/UBERON_0000029

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Comment by paolaroncaglia** [comment]
Note to self: 
Nancy requested lymph node interfollicular cortex;
1) UBERON:0010417 'lymph node T cell domain' is defined as "The paracortex and interfollicular cortex of the lymph node in which T lymphocytes home to survey dendritic cells";
so should the new term be part_of it?
2) The recently created, not-yet-released UBERON:8410036 'medullary venule of lymph node' is defined as "Medullary venules are a continuation of high endothelial venules which condense repeatedly in the interfollicular cortex and peripheral deep cortical unit and then transition to medullary venules at the corticomedullary junction. The medullary venules condense and return centripetally to the hilar vein.";
so should the new term be linked to it?

**Comment by addiehl** [comment]
1. I agree this new term should be part_of 'lymph node T cell domain', based on that term's definition.

2. I don't think there's a need to link 'lymph node interfollicular cortex' to 'medullary venule of lymph node' because the latter term refers to a blood vessel that seemingly may span multiple parts of the lymph node. But I don't fully understand the definition of 'medullary venule of lymph node':  Are medullary venues only at the corticomedullary junction or are they also part of the interfollicular cortex and peripheral deep cortical unit?  I think the definition favors the first interpretation but could be read to favor the second.  Are medullary venules a type of high endothelial venule, or a separate type of entity?

-- Alex

**Comment by paolaroncaglia** [comment]
Note to self: 
- [ ] Add as subclass of (_not_ equivalent to) 'cortex' and part of 'lymph node T cell domain'
- [ ] Address Alex' question on medullary venules separately.

**Comment by paolaroncaglia** [comment]
@ngeorgeebi and @sfexova 
UBERON:8410067 lymph node interfollicular cortex

**Comment by paolaroncaglia** [comment]
Note to self: left to do:
- [ ] Address Alex' question 2 here https://github.com/obophenotype/uberon/issues/1809#issuecomment-857165004.

**Comment by paolaroncaglia** [comment]
Discussed at curators meeting today, @ngeorgeebi  will address. Thanks.

**Comment by paolaroncaglia** [comment]
I added the requested Uberon term previously, so I'll close this ticket.
@ngeorgeebi if you wish to address Alex' question as per last two comments above, please feel free to comment tagging both of us, and I'll reopen the ticket if needed. 
Thanks,
Paola
