### ISSUE TITLE
Revise UBERON:0001153 'caecum' and UBERON:0001155 'colon'

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/uberon#1869]
Background/rationale:
Our collaborators at the Single Cell Expression Atlas (EBI) are working on anatomograms to visualize human data. 
In particular, they’re addressing the large intestine. As discussed previously, due to the technical details of their anatomograms set-up, they need to ensure that there is a distinction among cell types located in 
a) the appendix 
b) the anal canal 
c) the colon.   
For this reason, as agreed previously, we’re creating specific cell type and anatomy terms for SCA.
For the same reason, they’d need to ensure that the existing term for ‘colon’ (UBERON:0001155) excludes the vermiform appendix and the anal canal.
Currently, vermiform appendix is part of caecum, and caecum is part of colon (and of large intestine).
It is also 'continuous with' some 'ascending colon’.
The definition of ‘caecum’ is “A pouch in the digestive tract that connects the ileum with the ascending colon of the large intestine. It is separated from the ileum by the ileocecal valve, and is the beginning of the large intestine. _It is also separated from the colon_ by the cecocolic junction.”
- [x] Would it be fair to delete the axiom
caecum ‘part of’ some colon
please? [Update: revised, see below]
- [x] Also, would there be objections to edit the definition of colon from current
“Last portion of the large intestine before it becomes the rectum.”
to “A portion of the large intestine before it becomes the rectum. In mammals, the colon is the most part of the large intestine, excluding the vermiform appendix and the anal canal.”
please? [Update: revised, see below]
@sfexova may be able to suggest references to support the revised definition. I wonder if we could go as far as to make ‘colon’ disjoint from ‘vermiform appendix’ and ‘anal canal’. 

I realise that there are complications due to the different anatomical aspects in diverse species, but hopefully we can reach a consensus quickly (at least on adding a mammalian-focused gloss to the textual definition of colon) as it will affect the details of several existing term requests for anatomograms. Note that ‘colon’ has an ”editor note: TODO - abstract this such that it legitimately covers all vertebrates”.
  
Many thanks,
Paola

**Comment by cmungall** [comment]
I agree with all the above

**Comment by sfexova** [comment]
Hi @paolaroncaglia thanks very much for looking into this and for the very useful discussion we've had on this topic earlier today.
Yes, exactly for the anatomograms we need to have three sets of cell type/tissue annotations that are at the same level ontologically (not parent/child) for appendix, anal canal and 'everything else'. As said I thought we could call the 'everything else' group 'colon' but I see from your notes and also from reading more through various online human gut anatomy resources that it is probably a bit more complicated than that because although definitions of colon that I was able to find vary greatly, they do seem to exclude rectum and often also caecum and that would cause issues for us and the anatomogram pipeline. We could I think amend some of the annotations for our 'anal canal' image (as it represents the junction) from 'xy of anal canal' to 'xy of anorectum' to have a broader meaning that would cover rectum as well as anal canal but we would then need to 'stretch' the colon definition to include the caecum at least, which I do not think is incorrect as there definitely are source that consider caecum 'first part of colon' but then that is for humans and I am not sure how such a definition would work in terms of other vertebrates.

**Comment by paolaroncaglia** [comment]
Update: @sfexova and I discussed further offline. Silvie will ask their expert (a gut surgeon and researcher) to help us clarify whether the rectum should be included in the colon proper or not. I think not, but it's hard to say because most diagrams I find online seem to use colon interchangeably with large intestine (they depict appendix and caecum too). Perhaps one of us may also look up an authoritative human anatomy textbook to clarify the partonomy. Thanks.

**Comment by paolaroncaglia** [comment]
Update: @sfexova heard back from Mark Arends (University of Edinburgh):
"Based on anatomical and pathological textbooks (I have looked through many of both) and widespread usage in both anatomy and pathology,  the colon includes ileo-caecal valve (caecal component), caecum, ascending colon, hepatic flexure, transverse colon, splenic flexure, descending colon, sigmoid colon.
Colon does not include rectum, anal canal or appendix.
Large intestines (or large bowel) includes colon, rectum, appendix, anal canal."
Based on his input, I'd replace my suggestions in https://github.com/obophenotype/uberon/issues/1869#issue-899780660 with the following:

- [ ] For 'vermiform appendix' ("A blind-ended tube connected to the cecum, from which it develops embryologically[WP]."):
replace 
'part of' some caecum 
with 
'connected to' (or 'continuous with'? need to check) some caecum
This will ensure that appendix is not inferred as part of colon

- [ ] For 'colon': edit the definition from current
“Last portion of the large intestine before it becomes the rectum.”
to “A portion of the large intestine before it becomes the rectum. In mammals, the colon is the most part of the large intestine, excluding the vermiform appendix, the rectum and the anal canal.”

**Comment by RDruzinsky** [comment]
I think that you could define colon as part of the large intestine that has
omental appendages, since the vermiform appendix, caecum, and rectum do not
(well, most of the time). For vermiform appendix I like continuous with
some caecum rather than connected to.


Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
***@***.***

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by paolaroncaglia** [comment]
Hi @RDruzinsky ,

> I think that you could define colon as part of the large intestine that has omental appendages, since the vermiform appendix, caecum, and rectum do not (well, most of the time). For vermiform appendix I like continuous with some caecum rather than connected to. 

Many thanks for your feedback! The only concern with omental appendages would be that it'd exclude the caecum from the colon as you say, while other resources include it. So I'd rather avoid the potential conflict caused by "omental" if that makes sense. I do appreciate your advice though.

Best wishes,
Paola

**Comment by RDruzinsky** [comment]
You're welcome. However, I would caution that many anatomists and
authoritative textbooks, including the British Gray's, do not consider the
caecum to be part of the colon.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
***@***.***

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by paolaroncaglia** [comment]
> I would caution that many anatomists and authoritative textbooks, including the British Gray's, do not consider the caecum to be part of the colon.

Yes, I'm realizing that clear-cut partonomy consensus is not always easy to achieve...

**Comment by RDruzinsky** [comment]
You aren't kidding!

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
***@***.***

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by paolaroncaglia** [comment]
Note to self: I'll go ahead with the edits outlined in https://github.com/obophenotype/uberon/issues/1869#issuecomment-848896632.

**Comment by paolaroncaglia** [comment]
@sfexova 
I edited the Uberon term for 'vermiform appendix' so that it can't be inferred to be part of the colon.
It's part of the large intestine, but not of the colon.
Shall I go ahead and address the SCA tickets for appendix-related terms, or would you prefer me to wait further? Either is fine with me, as long as we're sure and I can ideally avoid to edit terms twice :-) 
Thanks,
Paola

**Comment by sfexova** [comment]
@paolaroncaglia
yes, there are - to my knowledge - no outstanding issues with the appendix cohort of terms and we should be good to go there
