### ISSUE TITLE
defining midpoints or midlines parts

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1870]
What is the best practice for defining a midpoint of some structure?

**Comment by paolaroncaglia** [comment]
Hi @megbalk ,

> What is the best practice for defining a midpoint of some structure?

I'm not sure; I did some searches but don't really have an answer. Is this request still current/needed - and were you able to find documentation, or discuss with others since this ticket was opened? If yes, please close this ticket. If not, please add to the agenda for discussion at the next Uberon editors' meeting, or tag someone who might help. I'll assign to you for now, but feel free to close if out-of-date. Thanks.

**Comment by megbalk** [comment]
@paolaroncaglia I'll add this to the agenda. Where do I find the agenda?

**Comment by paolaroncaglia** [comment]
Hi @megbalk ,

> I'll add this to the agenda. Where do I find the agenda?

It's [here](https://docs.google.com/document/d/1XvMbNvr0FEsdqGhg79BYCYEHSqUxRHMcvhbGizEAht8/edit#). Thanks!

**Comment by megbalk** [comment]
done!

**Comment by megbalk** [comment]
@bvarner-ebi suggested using [midsagittal plane](https://www.ebi.ac.uk/ols/ontologies/bspo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBSPO_0000009), which I will look into.
@shawntanzk also suggested using "[middle](http://www.ontobee.org/ontology/FMA?iri=http://purl.obolibrary.org/obo/FMA_74544)"
