### ISSUE TITLE
circular references

### ISSUE THREAD

**Issue by tutajm** [obophenotype/uberon#1967]
In July 6, 2021 release, and in todays' release, there is a circular reference between these two terms:

[Term]
id: UBERON:0002354
name: cardiac Purkinje fiber
relationship: part_of UBERON:8000009 ! Purkinje fiber network

[Term]
id: UBERON:8000009
name: Purkinje fiber network
relationship: part_of UBERON:0002354 ! cardiac Purkinje fiber

Is this intended? We did not see this issue before. We use the file: http://purl.obolibrary.org/obo/uberon/basic.obo

Thank you,
Marek

**Comment by matentzn** [comment]
Thank you @tutajm we will deal with this shortly.

**Comment by paolaroncaglia** [comment]
Dear @tutajm ,
Many thanks for bringing this to our attention. It should be fixed now (Purkinje fiber network has_part cardiac Purkinje fiber, instead of part_of). However, the fix won't be visible until Uberon is released again.
@matentzn @nicolevasilevsky @cmungall should we do a patch release? I see that Nico's working on re-instating a check for circular refs, are there any others that might have slipped in?
Thanks,
Paola

**Comment by matentzn** [comment]
Yes, your fix worked @paolaroncaglia.. I will see we have another release soon!

**Comment by matentzn** [comment]
Can you check whether this is fixe now in the latest release @tutajm ?

**Comment by dosumis** [comment]
@rays22  - please check if this is fixed and if so close.

**Comment by rays22** [comment]
Seems to be fixed.
