### ISSUE TITLE
Add term synaptosomes MeSH Unique ID: D013574 to Uberon ontology

### ISSUE THREAD

**Issue by Rahi13** [obophenotype/uberon#2036]

**Comment by paolaroncaglia** [comment]
Dear @Rahi13 ,
'synaptosome' would be in scope for the Gene Ontology (as a cellular component term) rather than the Uberon anatomy ontology. However, I suspect that it's not in GO either because it appears to be mostly an artefact of experimental isolation, see https://en.wikipedia.org/wiki/Synaptosome. @shawntanzk or @dosumis , let me know if you disagree. 
If synaptosome isn't in scope for GO, depending on your use case perhaps you could use one or more GO terms that are children (including part of) GO:0045202 'synapse'. Otherwise, if you still need to capture synaptosome as such, it should be requested to a different ontology, but I'm not sure which one would be appropriate. 
Best wishes,
Paola
