### ISSUE TITLE
Creating procedures for imports

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2094]
Current solution to messy imports should be to refresh imports in related ontologies when a release is made. This requires knowledge of import links so we can come up with the order in which is best to refresh import.

@shawntanzk to create an ontology dependency list and figure out a procedure on what should get imported first etc.

**Comment by shawntanzk** [comment]
![Screenshot 2021-10-12 at 09 01 04](https://user-images.githubusercontent.com/76212760/136916281-5189293f-0a79-4197-af36-39cf866abb98.png)

**Comment by shawntanzk** [comment]
Only way to do this is to solve this is using base files rather than full ontologies 
note: too complex to deal with individual basis @matentzn to handle this on ODK side
related to https://github.com/INCATools/ontology-development-kit/pull/252

**Comment by paolaroncaglia** [comment]
Hi @shawntanzk , cc @dosumis and @matentzn , 
Is there any update on this issue, please? I can't help with the technical stuff, but it seems that until this is fixed, among other inconveniences terms in the Single Cell Atlas anatomograms will be represented incorrectly (in fact, their pipeline might break, as reported in https://github.com/obophenotype/cell-ontology/issues/1120#issuecomment-956053403). 
Thanks in advance for any follow-up, I might have missed some relevant communication, too many GitHub notifications ;-)

**Comment by shawntanzk** [comment]
@paolaroncaglia this wont be a quick fix i think, but i think the bigger problem is the comment you linked needs an uberon release. Is the term fixed in uberon already? Cause if it is, once uberon is released, can try to fix it without the need to fully untangle the above.

**Comment by paolaroncaglia** [comment]
@shawntanzk thanks for your prompt reply. The thing is, the CL term that originated the discussion was created quite some tiem ago, and the relevant Uberon edits were made quite some time ago, and both CL and Uberon had been released at least once since; in fact I remember with a fair degree of certainty that the anatomy changes had even percolated to Mondo and EFO. Then something happened, please see conversation between David and myself below the comment I linked to.

**Comment by paolaroncaglia** [comment]
That said, if you think there's anything I can do to CL or Uberon that could help, let me know 
(I realize that sounds a bit menacing...)

**Comment by shawntanzk** [comment]
In my mind, what needs to happen (I might be wrong) is the following in order:

1) delete axioms from imports that are causing the error in uberon (this I need your help with cause I can't follow the thread attached, but I assume the cyclical issue is that an import is cyclically importing something that you want out)
2) Make and uberon release with IMP=false 
3) Refresh CL import of uberon and make sure the unwanted axiom isn't there, if not remove it
4) make a CL release
5) refresh the uberon import of CL

@matentzn the above should fix an issue with cyclical errors right? or am I missing something that would in the end requires the base file fix?

**Comment by paolaroncaglia** [comment]
@shawntanzk thanks. I won't touch anything for now, but will be happy to help if I can once we have confirmation of the best procedure.

**Comment by dosumis** [comment]
I've been scared of hitting this problem for years.  Zombie axioms are an inevitable result of circular import dependencies + imports pulling imported content. I think it might become a regular occurrence now we're doing lots of interdependent edits. Base files are the obvious solution (no imports of imports).  As I understand it, the problem is that this => incomplete imports (we don't get all dependencies of dependencies) unless we import everything from one huge merged ontology.  But maybe slightly incomplete is fine?

**Comment by matentzn** [comment]
My favourite problem. Given the huge amount of memory Uberon requires anyways, it would be a good candidate to try the base-merge-extract-prune workflow. To get this done I need a developer like @anitacaron or @hkir-dev for ~5 days straight, it can be done.

**Comment by paolaroncaglia** [comment]
(We should definitely have a "reaction" or label for "can of worms"...)

**Comment by matentzn** [comment]
🪱

**Comment by shawntanzk** [comment]
Will close this ticket as ontologies start implementing base file approach. Please open tickets in own ontologies issue tracker for implementation there (happy to bring those tickets to tech board if need be)
