### ISSUE TITLE
NTR: parasympathetic cholinergic nerve

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/uberon#2104]
@emquardokus (cc @dosumis, please see question below)

**Preferred term label:**
parasympathetic cholinergic nerve

**Definition (free text, please give PubMed ID)**
A parasympathetic nerve that releases acetylcholine.
PMID:24676230

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
'parasympathetic nerve'
overlaps some 'cholinergic neuron'? (This would be similar to how 'cholinergic enteric nerve' is modelled)
present in taxon Homo sapiens

For reference, this request stems from https://github.com/obophenotype/cell-ontology/issues/1279.

**Comment by dosumis** [comment]
CC @tgbugs

**Comment by tgbugs** [comment]
This prompted me to look again at how these cases were handled, and I think that the right thing to do here is to update the modelling so that we wind up with parasypathetic cholinergic neuron projection bundle, because I think that there are very few cases of nerves that are purely cholinergic (though some branches might be). We have been working to develop clearer definitions for nerves, nerve branches, fiber bundles, etc., but they aren't quite ready.
