### ISSUE TITLE
Harderian gland has inconsistent taxon constraints

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#2235]
[Harderian gland](http://purl.obolibrary.org/obo/UBERON_0004187) says:
- [never in taxon](http://purl.obolibrary.org/obo/RO_0002161) [Carnivora](http://purl.obolibrary.org/obo/NCBITaxon_33554)
- [present_in_taxon](http://purl.obolibrary.org/obo/RO_0002175) [Canidae](http://purl.obolibrary.org/obo/NCBITaxon_9608)
- [present_in_taxon](http://purl.obolibrary.org/obo/RO_0002175) [Felidae](http://purl.obolibrary.org/obo/NCBITaxon_9681)

Canids and felids are carnivorans. Found while implementing https://github.com/ontodev/robot/issues/963.

**Comment by cmungall** [comment]
Good catch! So glad to see the expansions fixed!

here it is with provenance

relationship: never_in_taxon NCBITaxon:33554 {source="PMID:7559104"} !
Carnivora
relationship: never_in_taxon NCBITaxon:9397 {source="PMID:7559104"} !
Chiroptera
relationship: never_in_taxon NCBITaxon:9443 {source="PMID:7559104"} !
Primates
relationship: never_in_taxon NCBITaxon:9606 {notes="may be transient in
embryos", source="PMID:7559104"} ! Homo sapiens
relationship: never_in_taxon NCBITaxon:9787 {source="PMID:7559104"} !
Perissodactyla
relationship: only_in_taxon NCBITaxon:32523 {source="PMID:7559104"} !
Tetrapoda
relationship: present_in_taxon NCBITaxon:10047 {source="ISBN:1118473523"}
relationship: present_in_taxon NCBITaxon:8293 {source="
https://sourceforge.net/p/geneontology/ontology-requests/10639"} ! Caudata
relationship: present_in_taxon NCBITaxon:8342 {source="
https://sourceforge.net/p/geneontology/ontology-requests/10639"} ! Anura
relationship: present_in_taxon NCBITaxon:9263 {source="
https://sourceforge.net/p/geneontology/ontology-requests/10639"} !
Metatheria
relationship: present_in_taxon NCBITaxon:9397 {source="PMID:20665821",
source="https://sourceforge.net/p/geneontology/ontology-requests/10639"} !
Chiroptera
relationship: present_in_taxon NCBITaxon:9608 {source="PMID:14803383",
source="https://sourceforge.net/p/geneontology/ontology-requests/10639"} !
Canidae
relationship: present_in_taxon NCBITaxon:9681 {source="PMID:6997222 ",
source="https://sourceforge.net/p/geneontology/ontology-requests/10639"} !
Felidae

Previous issue:
https://github.com/obophenotype/uberon/issues/392

The SF issues is mapped to this GO github one, originally handled by David
https://github.com/geneontology/go-ontology/issues/10825

It's a long time since I looked at it, and I haven't looked at the
publications again, but I suspect this is a case of older literature making
a too strong blanket statement, contravened by newer literature. If no one
is able to take a deep dive we should just take off carnivore

aside: the tax id missing a label should be investigated.
