### ISSUE TITLE
Add DOSDP checks to CI config

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2284]
From @dosumis 
" I hacked the main makefile test goal to in [this branch](https://github.com/obophenotype/uberon/pull/2231/files?file-filters%5B%5D=No+extension&show-deleted-files=false&show-viewed-files=false#diff-1376bbad1ef43bed6c9aed84b7d52471e63c87277b2b3f72ed0a5bdef481b638L61) ensure patterns were tested on PR, but I believe this needs to be set in CI config (Nico pointed out how to me somewhere last week, but don't remember where). Can this be set properly?  And shouldn't ODK config set this when dosdp=True - at the very least, basic schema checks should run.

**Comment by shawntanzk** [comment]
related to https://github.com/INCATools/ontology-development-kit/issues/534

**Comment by gouttegd** [comment]
Nothing to be done on the ODK side, the fix is already there.

In Uberon, this will be automatically fixed when we’ll update the repository after the next ODK release. What we can do in the meantime is to override the `test` goal in `uberon.Makefile`, but then we‘ll need to take care of removing the override when it’s no longer needed (when ODK 1.2.33 is out).

**Comment by shawntanzk** [comment]
@gouttegd will add a dev makefile for the time being that will implement the changes in 1.2.33 and will fix it

**Comment by gouttegd** [comment]
No longer relevant since PR #2231 was merged, and it contains a similar fix by David.
