### ISSUE TITLE
Switching mba/dmba to uberon bridges 

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2526]
Currently on building release there are 3 unsats from xrefs: 
```
UNSAT: DMBA:15612 DMBA:15612
UNSAT: MBA:30 MBA:30
UNSAT: MBA:689 MBA:689
NUMBER_OF_UNSATISFIABLE_CLASSES: 3

```
These are from our efforts to add new terms as we are re-doing mba and dmba bridge to uberon to be more accurate: https://github.com/obophenotype/uberon/pull/2484 

I'm not 100% sure what is causing the unsats but I guess this is as good as anytime to switch over the bridge files 

We have generated new bridges that are manually curated here: 
uberon-bridge-to-dmba.owl: https://github.com/obophenotype/ABA_Uberon/blob/new_bridge/src/ontology/new-bridges/new-uberon-bridge-to-dmba.owl
uberon-bridge-to-mba.owl: https://github.com/obophenotype/ABA_Uberon/blob/new_bridge/src/ontology/new-bridges/new-uberon-bridge-to-mba.owl

I would like to stop these two files from generating through xrefs and instead download from that repo and use that - I'm however not super sure how to handle this 

Was wondering if @matentzn and/or @gouttegd could help me out with this :) 

From there I'm hoping with the new fixes, unsats will go away, if not we will investigate what is going on.

Thanks!

**Comment by shawntanzk** [comment]
ps if we want a release out before we can get to this, I'm also happy to remove those xrefs - given the end goal will be to use the new bridge files anyway

**Comment by gouttegd** [comment]
Probably won't have a look at that until next week, so if a release needs to be done maybe you could indeed just remove the offending xrefs for now.

Longer term, I'd really like to avoid accumulating different ad-hoc solutions to deal with/generate bridge files. There's already the FBbt bridge files that are treated differently from all the others (since I used them to start testing SSSOM). I'd like to have a generalized, ODK-managed solution for all bridges -- I was planning to work on that as soon as we figure out 1) what property to use for cross-species mappings and 2) how do we "translate" a mapping predicate in a SSSOM mapping set to a OWL axiom that can be put in a bridge file.

**Comment by shawntanzk** [comment]
I like the idea of a generalised ODK-managed solution for bridges with good documentation of how to handle it etc. Happy to remove the 3 offending xrefs for now for release purposes.

**Comment by gouttegd** [comment]
I already kind of now how I'd want to do it, but we absolutely need to solve at least point 2) in my previous comment: we need a way to generate the bridging axiom from SSSOM. For now with FBbt I'm doing that with a AWK script, which is a hideous hack that nobody wants -- we need a method that is at the very least approved by the SSSOM folks, and ideally a method that is officially supported by the SSSOM tooling.

**Comment by shawntanzk** [comment]
I wonder if everything goes through SSSOM can we still have more expressive bridges? Currently we are using a ROBOT template because we need some to be equivalent, some to be subclass part of. And of course species specificity but I guess that part will be solved.

**Comment by gouttegd** [comment]
> can we still have more expressing bridges?

Maybe not with SSSOM. I'm pretty sure one of the “S” stands for “simple”, after all...

But we can still have a dual solution with SSSOM-generated simple bridges, and custom, template-based bridges for more complex situations. But even for those, I'd like them to be managed by the ODK in a standardized fashion, so that we don't end up with 10 custom solutions if 10 different people need complex bridges...

**Comment by gouttegd** [comment]
Disabling the xref-based bridge generation for a particular ontology should only require removing the corresponding treat-xref-as statement in uberon-edit.obo.

**Comment by shawntanzk** [comment]
ok realised I shouldnt treat bridge like a normal component, cause it ends up bringing in all the mba and dmba terms and dangling classes. Not 100% sure how to handle it but I'm going to make a draft PR to start and maybe we can start figuring out what the best way to handle it from there is

**Comment by gouttegd** [comment]
I'd think that it should be *provided* (to consumers of the ontology) as a component but not *imported* in the ontology itself?

The current bridges are never imported in Uberon itself. We generate them, provide them, and then it's up to whoever needs a merged ontology to use them (e.g. for Ubergrap or SCAO).

**Comment by shawntanzk** [comment]
completed, however, still need to move the whole process to uberon - see ticket https://github.com/obophenotype/uberon/issues/2537
