### ISSUE TITLE
Relationship of gallbladder terms is inconsistent

### ISSUE THREAD

**Issue by allenbaron** [obophenotype/uberon#2569]
## Uberon terms
1. gallbladder (UBERON:0002423) 
2. gallbladder primordium (UBERON:0006242)

## Suggested revision
Make `gallbladder` and `gallbladder primordium` subclasses of `biliary system` (UBERON:0002294) instead of `hepatobiliary system` (UBERON:0002423) and `biliary tree` (UBERON:0001173), respectively.

### Current relationships
![image](https://user-images.githubusercontent.com/21225409/178555135-19dff97c-d002-41d2-9e6c-7f35ba2101c7.png)

## Reasons
1. `biliary system` (UBERON:0002294) includes the `gallbladder` in its definition:
    > Organ system subdivision that consists of the organs and ducts that are involved in the production and transportation of bile. In most species this is the **_gallbladder_** and the bile ducts (biliary tree).

2. `gallbladder` and `gallbladder primordium` should have the same subclass of relationships given the definition of `gallbladder primordium`:
    >A sac-like cavity ventral to the liver, lying in the sub-mesodermal space and closed by a thin sheet of ectodermal cells, **_from which the future gall bladder develops_**.

3. The `biliary tree` as defined and as mentioned in the definition of `biliary system` appears to exclude the `gallbladder`, suggesting it should also exclude the `gallbladder primordium`.
    - `biliary system` definition:
        >Organ system subdivision that consists of the organs and ducts that are involved in the production and transportation of bile. In most species this is the _gallbladder **and** the bile ducts (biliary tree)_.

**Comment by shawntanzk** [comment]
Currently 'gall bladder' has the axioms: 
`'contributes to morphology of' some 'biliary tree'` & `'develops from' some 'gall bladder primordium'`
But because these are not part_of relations, they don't show on OLS 

biliary system has the equiv class axiom 
```
'organ system subdivision'
 and ('has part' some 'biliary tree')
 and ('capable of' some 'bile acid biosynthetic process')
 and ('capable of' some 'bile acid and bile salt transport')
```
biliary tree has the equiv class axiom
```
organ
 and ('part of' some 'biliary system')
 and ('composed primarily of' some 'bile duct')
```

I think that gall bladder is capable of both those processes, so having gall bladder be part_of biliary tree is fine I think (not sure if `'composed primarily of' some 'bile duct'` has implications on this - perhaps this was why the curator chose not that add part_of?), however 'gall bladder primordium' probably should not be under the system (I assume that because it develops into gall bladder, it isn't capable of those processes yet)

Therefore overall I think that the action item here would be:

- [ ] add `'part of' some 'biliary tree'` to `gall bladder`

I hope my modelling idea is right, not sure about implications on  `'contributes to morphology of' some 'biliary tree'` (together with partonomy and - might need a second opinion on this @dosumis 

Thanks!

**Comment by dosumis** [comment]
>  add 'part of' some 'biliary tree' to gall bladder

Perhaps better under 'billary system' as suggested by @allenbaron

Agree primordium should be removed from partonomy under tree

(ASIDE:  In some cases we do use a more specialised 'part of' relationship - for these it is worth discussing whether we should materialised 'part of' in the release process.  But in this case we could only infer overlaps.

![image](https://user-images.githubusercontent.com/112839/178682384-e4822719-4501-41e1-ae58-6f5e2484a517.png))
