### ISSUE TITLE
viscerocranium

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#2630]
**Uberon term**
facial skeleton

**Synonym to be added**
viscerocranium

**broad/exact/narrow/related ?**
exact

**Comment by uberon** [comment]
Viscerocranium is a term with a complex history. I think there are old
tickets about this. Will check later

**Comment by megbalk** [comment]
@uberon @shawntanzk @bvarner-ebi is this something to add to the agenda?

**Comment by cmungall** [comment]
Sorry, I must have imagined the previous tickets. Don't let me a blocker. However, I do recommend when requesting a new synonym that we search for existing classes that include that as a synonym and look at metadata for those synonyms
You can easily search for synonyms using OLS. If you are using an ontology browser that does not show clear matches for synonyms, stop using it!

I use OAK on the command line, but you can get similar info from OLS:

`uberon aliases t=viscerocranium`

|curie|pred|alias
|---|---|---|
|UBERON:0008895|rdfs:label|splanchnocranium
|UBERON:0008895|oio:hasExactSynonym|pharyngeal endoskeleton
|UBERON:0008895|oio:hasExactSynonym|viscerocranium
|UBERON:0008895|oio:hasRelatedSynonym|branchial arch skeleton
|UBERON:0008895|oio:hasRelatedSynonym|gill arch skeleton
|UBERON:0008895|oio:hasRelatedSynonym|pharyngeal arch
|UBERON:0008895|oio:hasRelatedSynonym|pharyngeal arch skeleton
|UBERON:0008895|oio:hasRelatedSynonym|pharyngeal skeleton
|UBERON:0008895|oio:hasRelatedSynonym|visceral cranium
|UBERON:0008895|oio:hasRelatedSynonym|visceral skeletal system
|UBERON:0008895|oio:hasRelatedSynonym|visceral skeleton
|UBERON:0011156|rdfs:label|facial skeleton
|UBERON:0011156|oio:hasExactSynonym|facial skeleton
|UBERON:0011156|oio:hasRelatedSynonym|facial bone
|UBERON:0011156|oio:hasRelatedSynonym|ossa facialia
|UBERON:0011156|oio:hasRelatedSynonym|ossa faciei
|UBERON:0011156|oio:hasRelatedSynonym|viscerocranium

So we can see that changing the existing scope from related to exact would yield an error, as we already have an exact on a different class!

We can look at the notes on these (some of this is very cryptic, sorry, but this is what we have to go on now)

id: UBERON:0008895
name: splanchnocranium
def: "Subdivision of endoskeleton derived from pharyngeal arches." [https://orcid.org/0000-0002-6601-2165, ISBN:0073040584, Wikipedia:Facial_skeleton]
synonym: "branchial arch skeleton" RELATED []
synonym: "gill arch skeleton" RELATED []
synonym: "pharyngeal arch" RELATED INCONSISTENT [VSAO:0000149]
synonym: "pharyngeal arch skeleton" RELATED [ZFA:0001216]
synonym: "pharyngeal endoskeleton" EXACT [http://orcid.org/0000-0002-6601-2165]
synonym: "pharyngeal skeleton" RELATED [ZFA:0001216]
synonym: "visceral cranium" RELATED [http://orcid.org/0000-0002-6601-2165]
synonym: "visceral skeletal system" RELATED [http://orcid.org/0000-0002-6601-2165]
synonym: "visceral skeleton" RELATED [UBERONREF:0000007]
**synonym: "viscerocranium" EXACT INCONSISTENT [VHOG:0000315, Wikipedia:Viscerocranium, ZFA:0001216]**

name: facial skeleton
def: "Subdivision of skull that consists of the facial bones." [http://www.bartleby.com/107/37.html, https://orcid.org/0000-0002-6601-2165, MP:0005274, Wikipedia:Facial_skeleton]
subset: pheno_slim
synonym: "facial bone" RELATED [MA:0000318]
synonym: "facial skeleton" EXACT [FMA:53673]
synonym: "ossa facialia" RELATED LATIN [Wikipedia:Facial_skeleton]
synonym: "ossa faciei" RELATED LATIN [Wikipedia:Facial_skeleton]
**synonym: "viscerocranium" RELATED INCONSISTENT [MA:0000318]**

We can see these are tagged INCONSISTENT. If I had been more diligent I would have noted more sources when looking into this.

It turns out that all my notes are here when I proposed splitting the wikipedia page for facial skeleton:

https://en.wikipedia.org/wiki/Talk:Facial_skeleton#Split_proposal

_Splanchnocranium is typically defined in terms of developmental origin, whereas facial skeleton typically means literally the bones of the face._
_Splanchnocranium: the part of the endoskeleton derived from the [pharyngeal arches](https://en.wikipedia.org/wiki/Pharyngeal_arches) (see Kardong, above). Note that the endoskeleton is cartilage and the bones that replace the cartilage. Under this definition, the splanchnocranium includes the [hyoid bone](https://en.wikipedia.org/wiki/Hyoid_bone), [laryngeal cartilages](https://en.wikipedia.org/wiki/Laryngeal_cartilages) (note: not in the face), [Meckel's cartilage](https://en.wikipedia.org/wiki/Meckel%27s_cartilage), [malleus](https://en.wikipedia.org/wiki/Malleus), [incus](https://en.wikipedia.org/wiki/Incus), [stapes](https://en.wikipedia.org/wiki/Stapes) (also not in the face). It would exclude the [dentary](https://en.wikipedia.org/wiki/Dentary) (mandible) and the [maxilla](https://en.wikipedia.org/wiki/Maxilla) as these are dermal bones and therefore *not* endoskeleton. The same for the [lacrimal bone](https://en.wikipedia.org/wiki/Lacrimal_bone) and all the other dermal bones currently listed at the start of the article. Contrast with: facial skeleton / ossa faceie - the bones of the face, regardless of developmental origin. This includes the mandible, maxilla etc.
In fact there is very little overlap between these two sets of bones. The bones of the splanchnocranium need not be in the face. The actual bones that are in the face are largely dermal, and therefore do not fit the classic definition of splanchoncranium. [Cmungall](https://en.wikipedia.org/wiki/User:Cmungall) ([talk](https://en.wikipedia.org/wiki/User_talk:Cmungall)) 22:36, 2 December 2012 (UTC)_

It looks like the wikipedia editors acted on this, and this is now a disambiguation page:

https://en.wikipedia.org/wiki/Viscerocranium

**Comment by megbalk** [comment]
Thanks for the history. I would suggest creating the term viscerocranium and maybe making them related? However, it would require some detangling in OBA as the hierarchy is: viscerocranium morphology trait / facial skeleton size

**Comment by cmungall** [comment]
Always happy to do ontology archaeology!

Not sure what you are suggesting: by new term do you mean new class, or new synonym? I don't think either is necessary?

IMO the only valid change is to demote the UBERON:0008895 synonym to related, so as not to favor any one terminological system and avoid confusion

OBA and Uberon terminology should be consistent. it looks like this one came from VT https://www.ebi.ac.uk/ols/ontologies/oba/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBA_VT0005274

The VT term is just this term https://www.ebi.ac.uk/ols/ontologies/mp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMP_0005274

with abnormal taken off. 

Both VT and MP axiomatize to facial skeleton which is consistent with the MA synonym attribution

If we can get agreement here on the terminology we can propagate out to other ontologies

@sbello how would the mouse folks feel about using "facial skeleton" as the primary unambiguous label?

**Comment by megbalk** [comment]
if viscerocranium is inconsistent with facial skeleton, I was suggesting making a term viscerocranium as it is a useful term for users to search for trait terms. It seems the issue is that facial skeleton does not not include the mandible but the viscerocranium does?

I'd also note the definition of cranial skeleton does not make sense, it says includes the skull (cranium and mandible), with cranium being a subclass of skull.

**Comment by cmungall** [comment]
> if viscerocranium is inconsistent with facial skeleton, I was suggesting making a term viscerocranium as it is a useful term for users to search for trait terms

All systems implementing search should search on synonyms, so users can still search with viscerocranium, even if it is ambiguous.

Also I am not sure the issue as such is that viscerocranium is inconsistent with facial skeleton. It is that the string "viscerocranium" is ambiguous. Some communities (roughly: pan-vertebrate evodevo) use the string "viscerocranium" to mean _endoskeleton derived from pharyngeal arches_. Other communities (possibly more prevalent) use the same string to mean "facial skeleton".

These two classes/concepts are actually radically different!

The problem is that we can't use an ambiguous string as the same primary label or exact synonym for two classes. So either one or both communities must lose out and have the string be demoted to a non-exact synonym for their class.

We need to work on the uberon documentation to make this clear - but this is all very standard for most OBO ontologies, including GO

There are 3 possibilities we can vote on:

viscerocranium is:

- related syn for both concepts
- exact syn or primary label for facial skeleton (UBERON:0011156)
- exact syn or primary label for splanchnocranium (UBERON:0008895)

> It seems the issue is that facial skeleton does not not include the mandible but the viscerocranium does?

That's not the issue here. And just to be pedantic [sorry], "viscerocranium" is ambiguous as far as uberon is concerned, so we'd have to phrase the question as "the issue is that facial skeleton does not not include the mandible but the splanchnocranium does"

In fact, the facial skeleton *does* include the mandible, 

* [] UBERON:0011156 ! facial skeleton
    * [p] UBERON:0001708 ! jaw skeleton
        * [p] **UBERON:0003278 ! skeleton of lower jaw**
            * [p] UBERON:0004742 ! dentary
                * [i] **UBERON:0001684 ! mandible**


> I'd also note the definition of cranial skeleton does not make sense, it says includes the skull (cranium and mandible), with cranium being a subclass of skull.

You can make a separate issue for this? Thanks!! (but remember to check to see if this hasn't been brought up before)

**Comment by megbalk** [comment]
It seems to relate to [issue #59](https://github.com/obophenotype/uberon/issues/59), but I'm unsure how to jump into that conversation

**Comment by cmungall** [comment]
There is a lot of historic information in that issue that is useful, but I'm not sure if it directly has a bearing on this one

Let me know how you'd like to proceed. Would you still like a new class? If so, what would it's definition be and how would it differ? Or would you like to change the existing synonym assignments?

**Comment by megbalk** [comment]
So we concluded that because there is a related synonym viscerocranium, this issue is no longer needed.
