### ISSUE TITLE
Provide Uberon mappings as canonical SSSOM files

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2833]
While we maintain bridge files for uses related to OWL logical integration, we frequently need more simple mappings for integrating external ontologies into Uberon, i.e. skos or semapv cross-species mappings. While we can obtain some mappings using OAK (using the oboInOwl:hasDBXref property) they have a few undesirable properties like a lot a good number of proxy merges (Uberon:nerve maps to Xenopus:nerve AND Xenopus:peripheral_nerve). 

This is not the same as (but related to) @gouttegd effort to moving the _maintainance_ of mappings to SSSOM format. This is about sharing the final set with the community.

**Comment by cmungall** [comment]
All such proxy merged functions in uberon should be intentional (and rare).
Uberon takes the position that in xao there are no nerves that are not
peripheral. The so called cranial nerves are not nerves. Ideally we would
open issues on external trackers for all such proxy merges

**Comment by matentzn** [comment]
Made a new issue for the proxy merge review and issue suggestion you made @cmungall: https://github.com/obophenotype/uberon/issues/2834

**Comment by gouttegd** [comment]
PR #3061 generates a SSSOM version of the mappings as part of the bridge generation process. For now this is an intermediate file (generated in `src/ontology/tmp`) that is not published, this could easily be changed.

**Comment by gouttegd** [comment]
More people are asking for this, we should really do it. The final set is built as part of the normal release pipeline, all we need to do is to treat it as a release product rather than as a temporary file.

**Comment by matentzn** [comment]
Do we need another `mappings` folder just off the repo root which contains the generated mappings in ODK? Especially for those ontologies that release on GitHub rather than as attachments to GitHub releases?

It would also be nice to get some basic "justification" stuff in there. Maybe as a second step.

**Comment by gouttegd** [comment]
> Do we need another mappings folder just off the repo root which contains the generated mappings in ODK?

That’s a discussion to be had on the ODK repo. I wouldn’t say we _need_ that, but that’s certainly one of the things that the ODK could help standardise (so that if you know that a given ontology follows the ODK workflows, then you know that you can find its mappings in `mappings/`).

> It would also be nice to get some basic "justification" stuff in there.

Not sure what you mean here. Justification for the decision to publish the Uberon mappings? Well, because as I’ve said some people want them, and ideally they don’t want to have to extract them from the ontology.

Or are you referring to the `mapping_justification` of the Uberon mappings? For now, they are all `semapv:UnspecifiedMatching`, because they are derived from xrefs and we cannot know what was the justification for those xrefs.

**Comment by gouttegd** [comment]
With #3249, the “meta“ mapping set will be available as a release artefact under the name `Uberon.sssom.tsv`.

With the default PURL redirection already in place, that artefact will be accessible at `http://purl.obolibrary.org/obo/uberon/uberon.sssom.tsv`, as soon as the next Uberon release happens.

**Comment by matentzn** [comment]
Aweeeesome!
