### ISSUE TITLE
subendocardium layer has_part nerve relation too general

### ISSUE THREAD

**Issue by leroybondhus** [obophenotype/uberon#2910]
**Uberon term**
UBERON:0005984 
subendocardium layer UBERON:0005984 has_part nerve UBERON:0001021

**Bug description**
transitive logic of has_part does not seem to be appropriate - when returning all descendant part of subendocardium layer using this relation, logic propagates to include inappropriate subclasses of nerve.

**Comment by balhoff** [comment]
Hi @leroybondhus in the case of an existential restriction, the logical propagation will be "up" instead of "down" the object class hierarchy. You can see all inferred parts of [subendocardium layer](http://purl.obolibrary.org/obo/UBERON_0005984) in this Ubergraph query: https://api.triplydb.com/s/jYWLZAG5w

**Comment by leroybondhus** [comment]
Ah I see - that makes sense
