### ISSUE TITLE
UBERON:0000949 endocrine system uses obsolete GO:0050886 endocrine process

### ISSUE THREAD

**Issue by raymond91125** [obophenotype/uberon#3019]
**Uberon term**
UBERON:0000949 endocrine system

**Suggested revision of logical definition**
'endocrine system' EquivalentTo 'non-connected functional system' and ('capable of' some 'endocrine process')

GO:0050886 endocrine process is to be obsoleted because it is ill defined.
https://github.com/geneontology/go-ontology/issues/17084
Perhaps change LD to something like (per https://github.com/obophenotype/cell-ontology/issues/1706)
'non-connected functional system' and 'capable of' some ('hormone secretion' and ('has target end location' some 'circulatory system'))

**Comment by aleixpuigb** [comment]
I agree with the LD that you propose, since looking at [this comment](https://github.com/geneontology/go-ontology/issues/17084#issuecomment-1376027350), 'endocrine hormone secretion' and 'regulation of endocrine secretion' are also planned to be obsoleted.

**Comment by aleixpuigb** [comment]
Uberon has problem with this LD because it is in obo format, and I might have to split it in Subclasses:

![image](https://github.com/obophenotype/uberon/assets/94959119/c90dbede-484c-4754-bd33-0b8029f71370)
![image](https://github.com/obophenotype/uberon/assets/94959119/b6deb14e-e2ee-4496-9548-db7dbdfe4512)

I will bring this ticket to the Uberon call.
