### ISSUE TITLE
nociceptor appears in both uberon and CL as different terms (UBERON edits)

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#3020]
CL:0000198 (pain receptor cell) has exact synonyms nociceptor and nocireceptor
UBERON:0035017 is labelled nociceptor and is a child of multi cell part structure (UBERON:0005162)
This makes nocireceptor both a cell and and a multi cell part structure, and also a bit domain separation breaky. 
I would suggest that CL:0000198 uses another predicate, maybe hasRelatedSynonym

**Comment by shawntanzk** [comment]
transferred this to uberon

**Comment by bvarner-ebi** [comment]
Thank you for reporting this, @shawntanzk.

May I propose the following edits:

**[UBERON:0035017 nociceptor](http://purl.obolibrary.org/obo/UBERON_0035017)**

- [ ] **Edit label:**
CURRENT: nociceptor
PROPOSED: ‘nociceptor nerve ending’

- [ ] **Edit text definition:**
CURRENT: “Peripheral receptors for pain. Nociceptors include receptors which are sensitive to painful mechanical stimuli, extreme heat or cold, and chemical stimuli. All nociceptors are free nerve endings.”
_annotation_: dbxref: MESH:A08.800.550.700.650
PROPOSED: “A peripheral terminal of a peripheral, afferent sensory pain receptor cell that is sensitive to injury or pain, usually caused by extreme thermal exposures, mechanical forces, or other noxious stimuli. The nociceptor nerve ending innervates target tissue and transduces noxious stimuli to the central nervous system via some axon(s).”
_annotation_: ‘see also’ https://meshb.nlm.nih.gov/record/ui?ui=D009619

**Edit synonym annotations:**
- [ ] related synonym: “nociceptor” 
CURRENT: _annotation_: dbxref: MESH:A08.800.550.700.650
PROPOSED: _annotation_: see also’ MESH:A08.675.650.915.875; ‘see also’ MESH:A08.800.950.875; ‘see also’ MESH:A11.671.650.915.875

- [ ] related synonym: “pain receptor” 
CURRENT: _annotation_: dbxref: MESH:A08.800.550.700.650
PROPOSED: _annotation_: ‘see also’ https://meshb.nlm.nih.gov/record/ui?ui=D009619

REASON: Unable to locate current MeSH TreeNumber; “MESH” prefix does not render link with TreeNumbers; requires MeSH Unique ID, so use ‘see also’ instead of database_cross_reference

- [ ] **Add SubClass Of:**
`‘part of’ some nociceptor`

----

**[CL:0000198 ‘pain receptor cell’](http://purl.obolibrary.org/obo/CL_0000198)**

**Edit synonym annotations:**
- [ ] add _annotation_ ‘see also’ https://meshb.nlm.nih.gov/record/ui?ui=D009619 to exact synonym “nociceptor”

- [ ] add _annotation_ ‘see also’ https://www.thefreedictionary.com/nocireceptor to exact synonym “nocireceptor”
