### ISSUE TITLE
GOGOEDITDIFF failling

### ISSUE THREAD

**Issue by dosumis** [obophenotype/uberon#3155]
Doesn't seem to get past docker setup step.

https://github.com/obophenotype/uberon/actions/runs/7251425720

Note sure if releated, but  looks like some of the commands are deprecated and might need updating.

**Comment by anitacaron** [comment]
The problem seems to be the low timeout to start docker, it's only 180 seconds. There's a [PR](https://github.com/docker-practice/actions-setup-docker/pull/29) increasing the timeout to 600, and it seems to solve the problem. We'll change the GHA to use [the branch that fixes it](https://github.com/docker-practice/actions-setup-docker/pull/29#issuecomment-1869175236), as a temporary fix.
