### ISSUE TITLE
"pancreas" (UBERON:0001264) not part of "digestive system" (UBERON:0001007) or "endocrine system" (UBERON:0000949)?

### ISSUE THREAD

**Issue by hdetering** [obophenotype/uberon#3208]
**Uberon term**
"pancreas" (UBERON:0001264)

**Suggested revision and reasons**
should be part of
  "digestive system" (UBERON:0001007) 
and
  "endocrine system" (UBERON:0000949)

It seems to be classified in the expected manner in
  Danio dangila (NCBITaxon:7954)
  Xenopus (NCBITaxon:8353)

**Comment by rays22** [comment]
I think most people would regard the pancreas, or at least the exocrine pancreas, as an anatomical entity that is part of the digestive system. 
According to the [Terminologia Anatomica](https://en.wikipedia.org/wiki/Terminologia_Anatomica) international standard for human anatomical terminology, the human pancreas is indeed part of the digestive system ([systema digestorum](https://ifaa.unifr.ch/Public/TNAEntryPage/auto/part/LAEN/TAH2275%20P1F%20EN.pdf)).
However, I would be careful with defining the entire pancreas as part of the digestive system in UBERON, because that would lead to the inference that any part of the [UBERON:0001264 pancreas](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001264) is part of the digestive system. Arguably, some cell types of the pancreas ([e.g. CL:0008024 pancreatic endocrine cells](http://purl.obolibrary.org/obo/CL_0008024)) are not part of the digestive system.
I will focus on the "digestive system" related part of your issue, because [UBERON:0000016 endocrine pancreas](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000016) has already been asserted as being part of the [UBERON:0000949 endocrine system](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000949?lang=en). I think it might cause problems in some use cases if the cell types of the endocrine pancreas were categorise as being part of the digestive system.  

Please note that both the [UBERON:0000016 endocrine pancreas](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000016) and the [UBERON:0000017 exocrine pancreas](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000017) are part of [UBERON:0001264 pancreas](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001264).

1. Although the [UBERON:2001371 pancreatic system](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_2001371) class has no textual definition, it is logically defined as part of both the [UBERON:0000949 endocrine system](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000949?lang=en) and the [UBERON:0001007 digestive system](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001007?lang=en). Is [UBERON:0001264 pancreas](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001264) meant to be equivalent (shadow class) to [UBERON:2001371 pancreatic system](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_2001371), or is the [UBERON:0001264 pancreas](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001264) meant to be a part of the [UBERON:2001371 pancreatic system](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_2001371)?
The later interpretation (and thereby asserting that "*[UBERON:0001264 pancreas](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001264) `part of` some [UBERON:2001371 pancreatic system](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_2001371)"*) would potentially solve this issue.
2. However, there are also separate terms for [UBERON:0000016 endocrine pancreas](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000016) and [UBERON:0000017 exocrine pancreas](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000017). The [UBERON:0000016 endocrine pancreas](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000016) has already been asserted to be part of the [UBERON:0000949 endocrine system](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000949?lang=en). However, the [UBERON:0000017 exocrine pancreas](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000017) has not been defined in UBERON as part of the [UBERON:0001007 digestive system](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001007).
Analogously with the endocrine pancreas, we could assert that [UBERON:0000017 exocrine pancreas](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000017) is part of the [UBERON:0001007 digestive system](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001007).

I favour solution 2., i.e. asserting that
```
exocrine pancreas part of some digestive system
```
.

**Comment by rays22** [comment]
> I favour solution 2., i.e. asserting that
> 
> ```
> exocrine pancreas part of some digestive system
> ```

See PR #3227 .
