### ISSUE TITLE
Tech: Version IRIs in bridge files

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#3438]
Right now the bridges are refreshed through SOP rather than piggy-bagging on any of the regular process link import refresh or release.

**Problem:** As discussed in #3434, the fact that bridges are not tied to releases makes version IRIs a bit weird because they may not correspond to any existing release, which means the version IRIs wont resolve, defeating the purpose of versioned PURLs.

@gouttegd suggested due to the fact:

> The problem is not that it is incomplete, it is that the bridge version IRIs are potentially wrong. Whenever the Uberon release happens on a different day than the day the bridges were last re-generated, the bridges end up with a version IRI that has a different date than the date of the Uberon release itself. This happened for example last August.

to drop the altogether.

My argument against this was that it is useful for downstream applications consuming the bridges to know _when they were last generated_.

**Proposal:** Without thinking, my first intuition was to couple bridge files to the release. However, this is not quite as trivial, as the accurate generation of bridge files requires updating the imports, which we have deliberately decoupled from the release process to reduce points of failures. 

Before making things complicated: I do not really care about version IRIs. My simple proposal is to replace `ontology-version` with `dc-modified` (http://purl.org/dc/terms/modified), and replace the header in bridges.dispatch by:

```
[__default]
ontology-iri: http://purl.obolibrary.org/obo/uberon/bridge/%filename.owl
dc-maintained: %date
```

That will satisfy my desire to look "how old a bridge is" and I hope @gouttegd wish to not include wrong version IRIs..

**Comment by gouttegd** [comment]
> Without thinking, my first intuition was to couple bridge files to the release. However, this is not quite as trivial, as the accurate generation of bridge files requires updating the imports, which we have deliberately decoupled from the release process to reduce points of failures.

It would still be possible to do that, if we decouple the refreshing of the mappings (which _must_ not happen at release time, for the very same reason we have deliberately decoupled the imports refresh from the release process: we don’t want to fetch anything from the outside world at release time) from the re-generation of the bridges.

There would be some caveats, though:

First, not all bridges are generated from the mappings. Some (so called “complex bridges“) are specifically obtained directly from remote sources. Right now, building the bridges at refresh time means that we don’t need to treat the “complex bridges“ separately. If we were to build the bridges at release time, we would need to separate the “non-complex bridges“ (which _can_ be built at release time, since they only depend on the mappings) from the “complex bridges“ (which would still need to be obtained at refresh time).

Second, having the bridges built at mappings refresh time is, if not strictly necessary, _very_ convenient to spot anything fishy in the mappings. If we somehow got a bogus mapping, it’s very difficult to figure that out just by looking at a diff on SSSOM files. A bogus axiom in one of the generated bridges, on the other hand, will typically stand out much more and would be much easier to spot. If the bridges are only re-generated at release time, then it is highly likely that a bogus mapping would only be spotted at the worst moment, deep in the middle of a release process.

> [__default]
> ontology-iri: http://purl.obolibrary.org/obo/uberon/bridge/%filename.owl
> dc-maintained: %date

Not possible right now. The “dispatch file“ has been designed solely for the needs of the Uberon bridge files, and it supports _only_ the handful of properties that were present in the original, Perl-generated bridges. `dc-maintained` is not one of them.

I can change that but that won’t happen overnight.

**Comment by gouttegd** [comment]
> Second, having the bridges built at mappings refresh time is, if not strictly necessary, very convenient to spot anything fishy in the mappings. If we somehow got a bogus mapping, it’s very difficult to figure that out just by looking at a diff on SSSOM files. A bogus axiom in one of the generated bridges, on the other hand, will typically stand out much more and would be much easier to spot. If the bridges are only re-generated at release time, then it is highly likely that a bogus mapping would only be spotted at the worst moment, deep in the middle of a release process.

Scratch that, it’s stupid. The vast majority of our mappings are _internally_ maintained (“the call comes from inside the house!”), only the FBbt mappings are fetched from a remote source (~~and those cannot possibly be bogus, I am the one maintaining them!~~). Well, and the CL mappings as well, but if there is a problem with those they can only be fixed with a new CL release anyway, so whether we detect the problem at “mappings refresh time“ or at “release time“ does not really matter.

**Comment by gouttegd** [comment]
> Without thinking, my first intuition was to couple bridge files to the release. However, this is not quite as trivial

Or maybe it is.

As I recall, the main reason the bridges are re-generated at the same time as the mappings are refreshed is for convenience. Anita wanted a single command that would refresh everything (imports, mappings, _and_ bridges) in one go, so I made a `refresh-external-resources` target that does exactly that.

But it should be straightforward to change that target so that it does _not_ remake the bridges, but just refreshes the imports, the mappings, the two externally maintained “complex bridges“, and the few other externally maintained components (like the “HRA subset“).

Then at release time, we can just re-generate the bridges, using the locally available mappings without fetching anything remote.
