### ISSUE TITLE
Uberon mapping to GTEx sites

### ISSUE THREAD

**Issue by dhimmel** [obophenotype/uberon#704]
I would like to incorporate GTEx gene expression data in my project which relies on Uberon for anatomical structure identification. Therefore, I would like to translate GTEx sample sites into Uberon or CL terms.

Since I know little about anatomy, I am seeking to crowdsource the difficult mappings. Contributors can get paid through Thinklab ([instructions here](http://thinklab.com/discussion/processing-gtex-for-tissue-specific-gene-expression/82#275)). We will cross-post the mappings here when done.

@fbastian, @cmungall mentioned that you are knowledgeable on these topics and may already have an Uberon-GTEx mapping. Also perhaps you have insight on [which gene expression resource we should use](http://thinklab.com/discussion/tissue-specific-gene-expression-resources/81).

**Comment by fbastian** [comment]
GTEx looks really great from our preliminary analyses. What data are you working on? The Affymetrix data from the GTEx pilot project, or the RNA-Seq data available since January?

We are going to integrate them all in our database of gene expression (see http://bgee.org), so we are going to annotate all Affymetrix and RNA-Seq samples to Uberon. The annotations might be done for July. The expression analyses for September. 

FYI, we have a professional curator on this, with intimate knowledge of Uberon. So either you quietly wait for us to do the work ;) Or you do it on your own because you can't wait, then we could check your mapping and integrate it into Bgee. Or we could share the effort, but our lead curator seems to think it's not a lot of work (yeah, I'm surprised, too).

**Comment by fbastian** [comment]
And, did I mention that the best resource to get human, normal-only gene expression is, of course, Bgee? :p If you're interested or have any question, you can contact me.

**Comment by dhimmel** [comment]
> GTEx looks really great from our preliminary analyses. What data are you working on? The Affymetrix data from the GTEx pilot project, or the RNA-Seq data available since January?

We were working with the RNA-Seq data -- our [current analysis is here](https://github.com/dhimmel/gtex/blob/93c3800cef1ced48b100d57b8d6efab831f8533b/gtex.ipynb).

> either you quietly wait for us to do the work ;) Or you do it on your own because you can't wait

I am leaning towards switching entirely to Bgee and if Bgee includes GTEx in time then that data will be in our network. There are only 54 sites so the mapping should be easy for the expert. Feel free to build off of [our partial mapping](http://thinklab.com/discussion/processing-gtex-for-tissue-specific-gene-expression/82#275). Also if your expert completes the mapping now, he or she can collect the Thinklab bounty.

> And, did I mention that the best resource to get human, normal-only gene expression is, of course, Bgee? If you're interested or have any question, you can contact me.

Okay I posted [our exact needs and would love your feedback](http://thinklab.com/discussion/tissue-specific-gene-expression-resources/81#278).

**Comment by dhimmel** [comment]
The GTEx team [provided us a mapping](http://thinklab.com/discussion/processing-gtex-for-tissue-specific-gene-expression/82#306), so I will close this issue.

**Comment by cmungall** [comment]
Just to provide a summary for people arriving at this thread:

 - GTEx provide their own uberon mapping
 - Bgee are working (have done?) a more precise mapping 

@fbastian is this a correct summary?

See also:
https://thinklab.com/discussion/processing-gtex-for-tissue-specific-gene-expression/82#15
