### ISSUE TITLE
UBERON:0002726	cervical spinal cord, subclass to create? for GTex annotation

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#725]
Hi Chris,

What do you think, creating

'C1 cervical spinal cord'
relationship: is_a UBERON:0002726 {gci_filler="NCBITaxon:9606", gci_relation="part_of"} ! cervical spinal cord

for mapping GTex Brain - Spinal cord (cervical c-1)' ?

Thank you for comments and help
Cheers,

Anne

**Comment by cmungall** [comment]
note we have:

```
        UBERON:0002726 ! cervical spinal cord
          [P] UBERON:0007714 ! cervical subsegment of spinal cord
            [I] UBERON:0006469 ! first cervical spinal cord segment ***
```

I prefer the Cn nomenclature, rather than spelling out the ordinal 
("first", "second", etc).

How should these be related to the vertebral segments?

**Comment by cmungall** [comment]
Can you suggest a definition pattern for Cn segments? Remember we have a C8. This makes sense for the nerves (C8 nerve goes *under* vertebra 7), maybe the segments are defined in terms of nerves, which are themselves defined in terms of vertebrae (over for C1-7, under for C8). But what about dermatomes?

**Comment by RDruzinsky** [comment]
Dermatomes, by definition, are regions innervated by the sensory neurons of
a given spinal nerve (or division of the trigeminal nerve for the head).



Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by cewall** [comment]
The nerves (C1-C8) are defined with respect to both spinal cord segments and somites (i.e., an anatomical and a developmental reason).  On each side of the body, each somite is innervated by a segment of the spinal cord and a segmental (spinal) nerve.  There are 8 cervical somites, therefore 8 spinal cord segments and 8 segmental nerves.


Vertebrae are defined as "intersegmental" because they are formed by the fusion of neighboring parts of somites (i.e., they form from more than one somite).  The upper part of the first cervical somite that becomes bone fuses to the base of the skull (the details of this pattern probably vary some across major taxonomic groups) and ossifies as part of the occipital bone, and so the C1 nerve travels between the base of the skull and the C1 vertebra.


Dermatomes (the skin that is innervated by a particular segmental nerve) will also correspond to somites.

Not sure if that helps.


Chris W.




________________________________

**Comment by cmungall** [comment]
Thanks both!

I realize my comment about dermatomes was confusing and not strictly relevant. There are actually two senses of this term:

 [UBERON:0004016](http://purl.obolibrary.org/obo/UBERON_0004016) ! dermatome *A transitional population of migrating mesenchymal cells that derive from somites and that will become dermal cells*
 [UBERON:0007121](http://purl.obolibrary.org/obo/UBERON_0007121) ! skin nerve field (aka dermatome) *A zone of skin that is mainly innervated by a single sensory nerve. A nerve field innervated by exactly one dorsal root is called a dermatome*

@RDruzinsky is of course correct. Dermatomes (sensu skin nerve fields) don't pose any particular problem here, and the number of these necessarily corresponds to the number of spinal nerve pairs.

I think when I mentioned dermatomes it was a brain fart, and I was thinking of the somite lineage to the *vertebral elements* (which is more relevant than those leading to the dermis), and @cewalls's comments get at the heart of the matter here. We need to choose the appropriate axis (anatomical vs developmental) for definitions and make sure things align (including the off-by-1/2 for vertebral elements and somites).

As an aside, I was looking at EHDAA2, which is usually very precise for lineage in humans, but I think there are some problems here (if you are reading this in email you may need to switch to the ticket on the github website). See image:

![ss](https://cloud.githubusercontent.com/assets/50745/8467831/7802697a-2018-11e5-81b0-4111a1705feb.png)

**Comment by cmungall** [comment]
I will close this, as we already have UBERON:0006469

However, I will link to this ticket from the ontology so any further discussion on improving representation welcome here
